# Generated by Django 6.0.6 on 2026-07-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('company_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_code', models.CharField(max_length=50, unique=True)),
                ('rating_name', models.CharField(max_length=255)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer_ratings',
            },
        ),
        migrations.CreateModel(
            name='CustomerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=50, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer_sources',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, unique=True)),
                ('type_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer_types',
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_code', models.CharField(max_length=50, unique=True)),
                ('tier_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'membership_tiers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('external_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('salutation', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('identity_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='branches.branch')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.company')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customerrating')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customersource')),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.customertype')),
                ('membership_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.membershiptier')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(max_length=100)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('source_system', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_accounts',
                'constraints': [models.UniqueConstraint(fields=('customer', 'account_number'), name='uq_customer_account_number')],
            },
        ),
        migrations.CreateModel(
            name='CustomerEmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('role_type', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField()),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('transfer_reason', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='customers.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_assignments', to='branches.employee')),
            ],
            options={
                'db_table': 'customer_employee_assignments',
                'indexes': [models.Index(fields=['customer'], name='customer_em_custome_df0398_idx'), models.Index(fields=['employee'], name='customer_em_employe_182e9a_idx'), models.Index(fields=['role_type'], name='customer_em_role_ty_22e651_idx'), models.Index(fields=['is_current'], name='customer_em_is_curr_a10ed5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch'], name='customers_branch__ca6960_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_phone_91048b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['identity_number'], name='customers_identit_03f5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['external_customer_id'], name='customers_externa_470469_idx'),
        ),
    ]
