# Generated by Django 6.0.6 on 2026-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='companies_phone_4e684b_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='companies_email_6c1508_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_phone_91048b_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
