# Generated by Django 6.0.6 on 2026-07-10 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaCallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(max_length=50, unique=True)),
                ('result_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sa_call_results',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaIcpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('icp_code', models.CharField(max_length=20, unique=True)),
                ('icp_name', models.CharField(max_length=255)),
                ('icp_type', models.CharField(choices=[('POTENTIAL', 'Tiềm năng'), ('NURTURE', 'Nuôi dưỡng'), ('NON_POTENTIAL', 'Không tiềm năng'), ('INVALID', 'Ảo / Không liên lạc')], default='NURTURE', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('follow_up_days', models.IntegerField(blank=True, null=True)),
                ('is_potential', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sa_icp_groups',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaInterestLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('level_code', models.CharField(max_length=50, unique=True)),
                ('level_name', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sa_interest_levels',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('record_code', models.CharField(max_length=50, unique=True)),
                ('account_no', models.CharField(db_index=True, max_length=50)),
                ('call_date', models.DateField()),
                ('follow_no', models.IntegerField(default=1)),
                ('reactivation', models.BooleanField(default=False)),
                ('reactivation_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('introduced_product', models.BooleanField(default=False)),
                ('support_info', models.BooleanField(default=False)),
                ('referred_rm', models.BooleanField(default=False)),
                ('transaction_fee_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('transaction_value_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('source_system', models.CharField(choices=[('CRM_MINI', 'CRM Mini'), ('CLOUDGO', 'CloudGo'), ('EXCEL', 'Excel')], default='CRM_MINI', max_length=50)),
                ('source_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_status', models.CharField(choices=[('VALID', 'Hợp lệ'), ('MISSING_ACCOUNT', 'Thiếu số tài khoản'), ('DUPLICATED', 'Trùng dữ liệu'), ('INVALID', 'Không hợp lệ')], default='VALID', max_length=50)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='branches.branch')),
                ('call_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sa_records', to='sale_admin.sacallresult')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='customers.company')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sa_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='customers.customer')),
                ('customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='customers.customeraccount')),
                ('icp_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='sale_admin.saicpgroup')),
                ('interest_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='sale_admin.sainterestlevel')),
                ('pic_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records_as_pic', to='branches.employee')),
                ('pic_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records_as_pic', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sa_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sa_records',
                'ordering': ['-call_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaRecordAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('IMPORT', 'Import')], max_length=50)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_record_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('sa_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='sale_admin.sarecord')),
            ],
            options={
                'db_table': 'sa_record_audit_logs',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['record_code'], name='sa_records_record__7ec893_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['account_no'], name='sa_records_account_73d87e_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['customer_account'], name='sa_records_custome_a20c01_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['customer'], name='sa_records_custome_caa0af_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['company'], name='sa_records_company_4e930e_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['branch'], name='sa_records_branch__8efb52_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['pic_user'], name='sa_records_pic_use_4a2ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['call_date'], name='sa_records_call_da_a7128b_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['call_result'], name='sa_records_call_re_4a1de2_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['icp_group'], name='sa_records_icp_gro_dfca47_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['reactivation'], name='sa_records_reactiv_d0382b_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['source_system'], name='sa_records_source__a05cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['data_status'], name='sa_records_data_st_ab66ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='sarecord',
            constraint=models.UniqueConstraint(fields=('account_no', 'pic_user', 'call_date', 'follow_no'), name='uq_sa_record_account_pic_date_follow'),
        ),
        migrations.AddConstraint(
            model_name='sarecord',
            constraint=models.UniqueConstraint(condition=models.Q(('source_call_id__isnull', False), models.Q(('source_call_id', ''), _negated=True)), fields=('source_system', 'source_call_id'), name='uq_sa_record_source_call'),
        ),
        migrations.AddIndex(
            model_name='sarecordauditlog',
            index=models.Index(fields=['sa_record'], name='sa_record_a_sa_reco_517277_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecordauditlog',
            index=models.Index(fields=['action_type'], name='sa_record_a_action__b26b35_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecordauditlog',
            index=models.Index(fields=['changed_by_user'], name='sa_record_a_changed_e58afb_idx'),
        ),
        migrations.AddIndex(
            model_name='sarecordauditlog',
            index=models.Index(fields=['changed_at'], name='sa_record_a_changed_fb0b49_idx'),
        ),
    ]
