# Generated by Django 6.0.6 on 2026-07-10 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
        ('sale_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sarecord',
            name='account_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='branch_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='broker_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records_as_broker', to='branches.employee'),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='broker_handover_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='broker_handover_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='broker_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records_as_broker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='handover_to_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='pic_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='vip_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
