from decimal import Decimal


DEFAULT_KPI_GROUPS = [
    {
        "group_code": "A",
        "group_name": "KPI Vận hành / Nghiệp vụ",
        "group_type": "MANUAL",
        "weight_percent": Decimal("60.00"),
        "sort_order": 1,
    },
    {
        "group_code": "B",
        "group_name": "KPI Sales / Doanh thu",
        "group_type": "AUTO",
        "weight_percent": Decimal("40.00"),
        "sort_order": 2,
    },
]


DEFAULT_KPI_PERIOD_METRICS = [
    {
        "group_code": "A",
        "metric_code": "A1",
        "metric_definition_code": "CONTACT_COMPLIANCE",
        "weight_percent": Decimal("10.00"),
        "sort_order": 1,
    },
    {
        "group_code": "A",
        "metric_code": "A2",
        "metric_definition_code": "ICP_ACCURACY",
        "weight_percent": Decimal("10.00"),
        "sort_order": 2,
    },
    {
        "group_code": "A",
        "metric_code": "A3",
        "metric_definition_code": "DATA_QUALITY",
        "weight_percent": Decimal("10.00"),
        "sort_order": 3,
    },
    {
        "group_code": "A",
        "metric_code": "A4",
        "metric_definition_code": "INTERNAL_COLLAB",
        "weight_percent": Decimal("10.00"),
        "sort_order": 4,
    },
    {
        "group_code": "A",
        "metric_code": "A5",
        "metric_definition_code": "REPORT_PROFILE",
        "weight_percent": Decimal("10.00"),
        "sort_order": 5,
    },
    {
        "group_code": "A",
        "metric_code": "A6",
        "metric_definition_code": "PROFESSIONAL_DEVELOPMENT",
        "weight_percent": Decimal("10.00"),
        "sort_order": 6,
    },

    {
        "group_code": "B",
        "metric_code": "B1",
        "metric_definition_code": "TOTAL_CALLS",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("100.00"),
        "sort_order": 1,
    },
    {
        "group_code": "B",
        "metric_code": "B2",
        "metric_definition_code": "REACTIVATED_ACCOUNTS",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("20.00"),
        "sort_order": 2,
    },
    {
        "group_code": "B",
        "metric_code": "B3",
        "metric_definition_code": "RETENTION_RATE",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("70.00"),
        "sort_order": 3,
    },
    {
        "group_code": "B",
        "metric_code": "B4",
        "metric_definition_code": "ICP_AB_CUSTOMERS",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("30.00"),
        "sort_order": 4,
    },
    {
        "group_code": "B",
        "metric_code": "B5",
        "metric_definition_code": "TOTAL_FEE",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("0.00"),
        "sort_order": 5,
    },
    {
        "group_code": "B",
        "metric_code": "B6",
        "metric_definition_code": "TOTAL_VALUE",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("0.00"),
        "sort_order": 6,
    },
    {
        "group_code": "B",
        "metric_code": "B7",
        "metric_definition_code": "INTRODUCED_PRODUCT_COUNT",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("10.00"),
        "sort_order": 7,
    },
    {
        "group_code": "B",
        "metric_code": "B8",
        "metric_definition_code": "ON_TIME_FOLLOWUP_RATE",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("80.00"),
        "sort_order": 8,
    },
    {
        "group_code": "B",
        "metric_code": "B9",
        "metric_definition_code": "RM_REFERRAL_COUNT",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("10.00"),
        "sort_order": 9,
    },
    {
        "group_code": "B",
        "metric_code": "B10",
        "metric_definition_code": "FAKE_REACTIVATION_RATE",
        "weight_percent": Decimal("4.00"),
        "target_value": Decimal("20.00"),
        "sort_order": 10,
    },
]


DEFAULT_REWARD_TIERS = [
    {
        "tier_code": "GOLD",
        "tier_name": "Vàng - PHÍ KÍCH HOẠT",
        "description": "Top 3 theo phí giao dịch phát sinh và đạt tất cả điều kiện cổng.",
        "rank_metric_code": "TOTAL_FEE",
        "rank_limit": 3,
        "min_total_score": None,
        "require_all_gates_passed": True,
        "reward_type": "CASH",
        "sort_order": 1,
    },
    {
        "tier_code": "SILVER",
        "tier_name": "Bạc - TK KÍCH HOẠT",
        "description": "Top 3 theo số tài khoản tái kích hoạt và đạt tất cả điều kiện cổng.",
        "rank_metric_code": "REACTIVATED_ACCOUNTS",
        "rank_limit": 3,
        "min_total_score": None,
        "require_all_gates_passed": True,
        "reward_type": "CASH",
        "sort_order": 2,
    },
    {
        "tier_code": "STANDARD",
        "tier_name": "Đạt chuẩn",
        "description": "Đạt chuẩn KPI và đạt tất cả điều kiện cổng.",
        "rank_metric_code": None,
        "rank_limit": None,
        "min_total_score": Decimal("70.00"),
        "require_all_gates_passed": True,
        "reward_type": "RECOGNITION",
        "sort_order": 3,
    },
    {
        "tier_code": "FAILED",
        "tier_name": "Chưa đạt",
        "description": "Không đạt điều kiện cổng hoặc tổng điểm dưới ngưỡng.",
        "rank_metric_code": None,
        "rank_limit": None,
        "min_total_score": None,
        "require_all_gates_passed": False,
        "reward_type": "IMPROVEMENT_PLAN",
        "sort_order": 4,
    },
]