from decimal import Decimal


DEFAULT_KPI_GROUPS = [
    {
        "group_code": "A1",
        "group_name": "Vận hành hàng ngày",
        "group_type": "MANUAL",
        "weight_percent": "36.00",
        "sort_order": 1,
    },
    {
        "group_code": "A2",
        "group_name": "Tham gia dự án",
        "group_type": "MANUAL",
        "weight_percent": "10.00",
        "sort_order": 2,
    },
    {
        "group_code": "A3",
        "group_name": "Tuân thủ & thái độ",
        "group_type": "MANUAL",
        "weight_percent": "5.00",
        "sort_order": 3,
    },
    {
        "group_code": "A4",
        "group_name": "Kiến thức & học hỏi",
        "group_type": "MANUAL",
        "weight_percent": "9.00",
        "sort_order": 4,
    },
    {
        "group_code": "B1",
        "group_name": "Gọi điện & tiếp cận KH inactive",
        "group_type": "AUTO",
        "weight_percent": "12.00",
        "sort_order": 5,
    },
    {
        "group_code": "B2",
        "group_name": "ICP - Phân nhóm KH trên CRM",
        "group_type": "AUTO",
        "weight_percent": "8.00",
        "sort_order": 6,
    },
    {
        "group_code": "B3",
        "group_name": "AAR - Tái kích hoạt giao dịch",
        "group_type": "AUTO",
        "weight_percent": "12.00",
        "sort_order": 7,
    },
    {
        "group_code": "B4",
        "group_name": "Hỗ trợ CSKH, giới thiệu SP và chuyển đổi nhóm KH",
        "group_type": "AUTO",
        "weight_percent": "8.00",
        "sort_order": 8,
    },
]

DEFAULT_KPI_PERIOD_METRICS = [
    {
        "metric_code": "A1_01",
        "definition_code": "ADMIN_OPEN_ACCOUNT",
        "group_code": "A1",
        "metric_name": "Mở Tài Khoản",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_open_account",
        "unit": "SCORE",
        "weight_percent": "7.00",
        "target_value": "100.00",
        "target_text": "0 lỗi HĐ; 0 TK trễ duyệt; 100% lưu trữ đúng",
        "frequency": "Tháng",
        "work_description": "Mở TK cơ sở & phái sinh: EKYC, form HĐ đúng đầy đủ, kiểm tra CCCD/passport/chữ ký, ghi âm xác nhận, gắn AF/ID, nhập Flex, hướng dẫn KH đăng nhập, lưu trữ HĐ đúng quy trình.",
        "measurement_formula": "(Số HĐ lỗi / Tổng HĐ) × 100%; KSNB hàng tháng; Log Flex; Ghi âm xác nhận",
        "sort_order": 1,
    },
    {
        "metric_code": "A1_02",
        "definition_code": "ADMIN_TRADE_ORDER",
        "group_code": "A1",
        "metric_name": "Lệnh Giao Dịch",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_trade_order",
        "unit": "SCORE",
        "weight_percent": "5.00",
        "target_value": "100.00",
        "target_text": "0 lỗi nhập lệnh; 100% kịp thời",
        "frequency": "Ngày",
        "work_description": "Nhận phiếu lệnh từ KH tại CN/PGD: kiểm tra CCCD, số TK, chứng khoán, tiền, chữ ký, nhập lệnh Flex, duyệt/in phiếu, đối chiếu file tổng và lưu trữ.",
        "measurement_formula": "(Số phiếu lỗi / Tổng phiếu) × 100%; Log Flex; KSNB spot check; File phiếu lệnh hàng ngày",
        "sort_order": 2,
    },
    {
        "metric_code": "A1_03",
        "definition_code": "ADMIN_SECURITIES_DEPOSITORY",
        "group_code": "A1",
        "metric_name": "Lưu Ký Chứng Khoán",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_securities_depository",
        "unit": "SCORE",
        "weight_percent": "7.00",
        "target_value": "100.00",
        "target_text": "100% đúng SLA; 0 hồ sơ trả lại",
        "frequency": "Tháng",
        "work_description": "Quyền mua, chuyển nhượng quyền mua, thay đổi thông tin nội bộ/VSDC, chuyển quyền sở hữu, phong tỏa/thừa kế, lưu ký/rút CK, đóng/chuyển TK.",
        "measurement_formula": "(Số hồ sơ đúng SLA / Tổng hồ sơ) × 100%; Base Workflow timestamp; VSDC confirmation; KSNB",
        "sort_order": 3,
    },
    {
        "metric_code": "A1_04",
        "definition_code": "ADMIN_CASH_TRANSFER_ADVANCE",
        "group_code": "A1",
        "metric_name": "GD Đăng ký, nộp, chuyển, ứng tiền",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_cash_transfer_advance",
        "unit": "SCORE",
        "weight_percent": "5.00",
        "target_value": "100.00",
        "target_text": "100% không lỗi",
        "frequency": "Ngày",
        "work_description": "Kiểm nộp tiền, chuyển khoản nội/ngoại, ĐKCT/thay đổi ĐKCT, ứng tiền, ứng cổ tức; kiểm tra CCCD, chữ ký, ghi âm, trình LM duyệt, lưu trữ.",
        "measurement_formula": "(Số GD lỗi / Tổng GD) × 100%; Chứng từ + ghi âm xác nhận; Log Flex/Portal; KSNB",
        "sort_order": 4,
    },
    {
        "metric_code": "A1_05",
        "definition_code": "ADMIN_MARGIN_TRANSACTION",
        "group_code": "A1",
        "metric_name": "Giao dịch Ký Quỹ",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_margin_transaction",
        "unit": "SCORE",
        "weight_percent": "7.00",
        "target_value": "100.00",
        "target_text": "0 sai sót số liệu; đúng quy định; kịp thời",
        "frequency": "Ngày",
        "work_description": "Mở TKKQ, cấp hạn mức Flex, quản lý/thống kê TKKQ, trả nợ MR&DP, gia hạn, check room, thông báo nợ hàng ngày, hỗ trợ tính ký quỹ KH VIP.",
        "measurement_formula": "(Số sai sót / Tổng nghiệp vụ ký quỹ) × 100%; Báo cáo nợ hàng ngày; Thống kê TKKQ tháng; KSNB",
        "sort_order": 5,
    },
    {
        "metric_code": "A1_06",
        "definition_code": "ADMIN_OTHER_TASKS",
        "group_code": "A1",
        "metric_name": "Các công việc khác",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_other_tasks",
        "unit": "SCORE",
        "weight_percent": "5.00",
        "target_value": "100.00",
        "target_text": "100% hoàn thành; đúng thời hạn",
        "frequency": "Khi phát sinh",
        "work_description": "Hỗ trợ nhân viên nghỉ phép, thủ tục cho NVQLTK, chứng từ KSNB, liên hệ tòa nhà, VPP, báo cáo GĐCN, chuyển KH nội bộ, kiểm kê tài sản, sự kiện PHS.",
        "measurement_formula": "(Số việc xong / Tổng việc được giao) × 100%; Xác nhận GĐCN; Biên bản KSNB; Base Wework/Base Workflow",
        "sort_order": 6,
    },
    {
        "metric_code": "A2_10",
        "definition_code": "ADMIN_PROJECT_IMPROVEMENT",
        "group_code": "A2",
        "metric_name": "Phối hợp dự án & đề xuất cải tiến",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_project_improvement",
        "unit": "SCORE",
        "weight_percent": "6.00",
        "target_value": "100.00",
        "target_text": "100% đúng hạn; ≥1 đề xuất/năm",
        "frequency": "Quý",
        "work_description": "Phối hợp dự án nâng cao chất lượng dịch vụ. Đề xuất cải tiến quy trình.",
        "measurement_formula": "(Task đúng hạn / Tổng task) × 100%; Base Wework; BOM approval",
        "sort_order": 10,
    },
    {
        "metric_code": "A2_11",
        "definition_code": "ADMIN_TOOL_TEST_SURVEY",
        "group_code": "A2",
        "metric_name": "Test công cụ & khảo sát mới",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_tool_test_survey",
        "unit": "SCORE",
        "weight_percent": "4.00",
        "target_value": "100.00",
        "target_text": "100% đúng hạn",
        "frequency": "Quý",
        "work_description": "Test link HĐ mới, công cụ mới. Hoàn thành khảo sát đúng hạn.",
        "measurement_formula": "(Test xong / Tổng việc được giao) × 100%; Test reports; Base Wework",
        "sort_order": 11,
    },
    {
        "metric_code": "A3_12",
        "definition_code": "ADMIN_COMPLIANCE_TEAMWORK",
        "group_code": "A3",
        "metric_name": "Tuân thủ nội quy & phối hợp team",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_compliance_teamwork",
        "unit": "SCORE",
        "weight_percent": "3.00",
        "target_value": "100.00",
        "target_text": "0 vi phạm",
        "frequency": "Quý / 6 tháng",
        "work_description": "Chấp hành nội quy. Hỗ trợ đồng nghiệp, giải quyết xung đột.",
        "measurement_formula": "Số vi phạm = 0; Biên bản; HR & LM review",
        "sort_order": 12,
    },
    {
        "metric_code": "A3_13",
        "definition_code": "ADMIN_COMPANY_EVENT",
        "group_code": "A3",
        "metric_name": "Tham gia sự kiện công ty",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_company_event",
        "unit": "PERCENT",
        "weight_percent": "2.00",
        "target_value": "90.00",
        "target_text": "≥90% sự kiện",
        "frequency": "6 tháng",
        "work_description": "Tham gia đầy đủ sự kiện nội bộ PHS.",
        "measurement_formula": "(Số sự kiện tham gia / Tổng sự kiện) × 100%; Danh sách sự kiện; HR & LM xác nhận",
        "sort_order": 13,
    },
    {
        "metric_code": "A4_14",
        "definition_code": "ADMIN_ELEARNING_TEST",
        "group_code": "A4",
        "metric_name": "Kiểm tra kiến thức E-learning",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_elearning_test",
        "unit": "PERCENT",
        "weight_percent": "3.00",
        "target_value": "80.00",
        "target_text": "≥80% điểm thi",
        "frequency": "6 tháng",
        "work_description": "Bài thi nghiệp vụ trên elearning.phs.vn.",
        "measurement_formula": "Điểm thi / Tổng điểm × 100%; Screenshot kết quả",
        "sort_order": 14,
    },
    {
        "metric_code": "A4_15",
        "definition_code": "ADMIN_CERTIFICATE_TRAINING",
        "group_code": "A4",
        "metric_name": "Chứng chỉ hành nghề & đào tạo",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_certificate_training",
        "unit": "PERCENT",
        "weight_percent": "3.00",
        "target_value": "90.00",
        "target_text": "100% chứng chỉ; ≥90% đào tạo",
        "frequency": "Năm",
        "work_description": "Hoàn thành chứng chỉ. Tham gia đào tạo HR & SS.",
        "measurement_formula": "(Số buổi tham gia / Tổng buổi) × 100%; Chứng chỉ; Attendance list",
        "sort_order": 15,
    },
    {
        "metric_code": "A4_16",
        "definition_code": "ADMIN_KNOWLEDGE_SHARING",
        "group_code": "A4",
        "metric_name": "Cập nhật kiến thức mới & chia sẻ",
        "kpi_type": "ADMIN",
        "input_type": "MANUAL",
        "formula_key": "manual_admin_knowledge_sharing",
        "unit": "SCORE",
        "weight_percent": "3.00",
        "target_value": "85.00",
        "target_text": "≥85% quiz; ≥1 đóng góp/năm",
        "frequency": "Khi phát sinh",
        "work_description": "Nắm quy định mới, sản phẩm mới. Chia sẻ kiến thức nội bộ.",
        "measurement_formula": "Điểm quiz × 100%; Số đóng góp ghi nhận; Feedback NVQLTK",
        "sort_order": 16,
    },
    {
        "metric_code": "B1_17",
        "definition_code": "SALE_CALLED_CUSTOMERS",
        "group_code": "B1",
        "metric_name": "Số KH được gọi / tháng",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_called_customers_month",
        "unit": "COUNT",
        "weight_percent": "8.00",
        "target_value": "100.00",
        "target_text": "Ngày: 5-10 KH; Tuần: 25-50; Tháng: ≥100 KH",
        "frequency": "Tuần",
        "work_description": "Gọi KH đã lâu không giao dịch, inactive trên 3-6 tháng. Khoảng 5-10 KH/ngày song song xử lý nghiệp vụ admin.",
        "measurement_formula": "CRM: Đếm KH outbound; Call log tự động từ CRM; File quản lý KH",
        "sort_order": 17,
    },
    {
        "metric_code": "B1_18",
        "definition_code": "SALE_CONTACT_RATE",
        "group_code": "B1",
        "metric_name": "Tỷ lệ liên lạc được",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_contact_rate",
        "unit": "PERCENT",
        "weight_percent": "4.00",
        "target_value": "30.00",
        "target_text": "≥30%",
        "frequency": "Tuần",
        "work_description": "Tỷ lệ KH nghe máy hoặc phản hồi khi SA gọi. Phản ánh chất lượng data và thời điểm gọi.",
        "measurement_formula": "(Số KH nghe máy / Tổng KH gọi) × 100%; CRM call tracking; Phân tích khung giờ hiệu quả",
        "sort_order": 18,
    },
    {
        "metric_code": "B2_20",
        "definition_code": "SALE_ICP_UPDATE_RATE",
        "group_code": "B2",
        "metric_name": "ICP: Cập nhật phân nhóm KH sau mỗi cuộc gọi",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_icp_update_rate",
        "unit": "PERCENT",
        "weight_percent": "4.00",
        "target_value": "100.00",
        "target_text": "100% KH gọi được phân nhóm trong ngày; 100% có ghi chú lý do theo chuẩn CRM",
        "frequency": "Ngày",
        "work_description": "Dựa trên phản hồi thực tế, phân KH vào các nhóm ICP trên CRM: rất tiềm năng, tiềm năng, nuôi dưỡng, ảo, không nghe máy.",
        "measurement_formula": "CRM: (KH phân nhóm + có ghi chú lý do / Tổng KH gọi) × 100%; Leader audit hàng tuần để coaching",
        "sort_order": 20,
    },
    {
        "metric_code": "B2_21",
        "definition_code": "SALE_DATA_QUALITY_RATE",
        "group_code": "B2",
        "metric_name": "ICP: Chất lượng data KH trên CRM",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_data_quality_rate",
        "unit": "PERCENT",
        "weight_percent": "4.00",
        "target_value": "98.00",
        "target_text": "≥98% data sạch; 0 sai sót nghiêm trọng",
        "frequency": "Tháng",
        "work_description": "Data chính xác, không trùng, đủ thông tin bắt buộc: SĐT, email, CCCD, nhóm ICP, trạng thái, lịch sử giao dịch.",
        "measurement_formula": "CRM: (Record sạch / Tổng record) × 100%; Random sample check hàng tháng; Báo cáo data quality từ CRM",
        "sort_order": 21,
    },
    {
        "metric_code": "B3_23",
        "definition_code": "SALE_AAR_REACTIVATED_CUSTOMERS",
        "group_code": "B3",
        "metric_name": "AAR: Số KH tái kích hoạt / tháng",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_aar_reactivated_customers",
        "unit": "COUNT",
        "weight_percent": "6.00",
        "target_value": "1.00",
        "target_text": "≥1 KH/6 tháng có ≥1 lệnh giao dịch mới",
        "frequency": "6 tháng",
        "work_description": "KH inactive không giao dịch trên 6 tháng được SA gọi và quay lại có ít nhất 1 giao dịch mới.",
        "measurement_formula": "CRM: Đếm KH chuyển inactive → active; AAR = Số KH tái GD / Tổng KH inactive được gọi × 100%; Mapping SA gọi → KH có GD mới",
        "sort_order": 23,
    },
    {
        "metric_code": "B3_24",
        "definition_code": "SALE_LTV_REACTIVATED_FEE",
        "group_code": "B3",
        "metric_name": "LTV: Phí GD phát sinh từ KH tái kích hoạt",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_ltv_reactivated_fee",
        "unit": "VND",
        "weight_percent": "4.00",
        "target_value": "10.00",
        "target_text": "≥10% tổng phí target hoặc theo LM giao",
        "frequency": "Tháng",
        "work_description": "Doanh thu phí giao dịch thực tế từ KH đã tái kích hoạt, chỉ tính phí khi TK KH vẫn ở IB và do SA chăm sóc.",
        "measurement_formula": "CRM: Tổng phí GD từ KH tái kích hoạt; Báo cáo phí Home/FLEX; Revenue report chi nhánh",
        "sort_order": 24,
    },
    {
        "metric_code": "B3_25",
        "definition_code": "SALE_REFERRAL_INTRO_RATE",
        "group_code": "B3",
        "metric_name": "Giới thiệu chương trình Referral cho KH",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_referral_intro_rate",
        "unit": "PERCENT",
        "weight_percent": "2.00",
        "target_value": "50.00",
        "target_text": "≥50% cuộc gọi với KH Tiềm năng & Rất tiềm năng có ghi chú đã giới thiệu Referral",
        "frequency": "Quý",
        "work_description": "SA chủ động nhắc chương trình Khách mời bạn bè với KH nhóm Tiềm năng/Rất tiềm năng trong mỗi cuộc gọi và ghi nhận vào CRM.",
        "measurement_formula": "CRM: (Cuộc gọi TP/RTP có note đã giới thiệu referral / Tổng cuộc gọi TP/RTP) × 100%; Leader kiểm tra call note hàng tuần",
        "sort_order": 25,
    },
    {
        "metric_code": "B4_26",
        "definition_code": "SALE_SUPPORT_SUCCESS_CUSTOMERS",
        "group_code": "B4",
        "metric_name": "Số KH được hỗ trợ chăm sóc thành công",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_support_success_customers",
        "unit": "COUNT",
        "weight_percent": "3.00",
        "target_value": "90.00",
        "target_text": "100% được hỗ trợ thành công; ≥90% feedback",
        "frequency": "Tháng",
        "work_description": "Hướng dẫn, hỗ trợ và chăm sóc khách hàng, giải đáp thắc mắc nghiệp vụ, log đầy đủ vào CRM.",
        "measurement_formula": "CRM: Số KH được SA liên hệ hỗ trợ trong tháng, có ghi note nội dung",
        "sort_order": 26,
    },
    {
        "metric_code": "B4_27",
        "definition_code": "SALE_NEW_PRODUCT_USERS",
        "group_code": "B4",
        "metric_name": "Số KH sử dụng dịch vụ/sản phẩm mới",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_new_product_users",
        "unit": "COUNT",
        "weight_percent": "2.00",
        "target_value": "1.00",
        "target_text": "≥1 KH/quý sử dụng sản phẩm mới",
        "frequency": "Quý",
        "work_description": "SA giới thiệu sản phẩm phù hợp ICP từng KH. Chỉ tính KH thực sự đăng ký/kích hoạt sản phẩm sau khi SA giới thiệu.",
        "measurement_formula": "CRM: Số KH đăng ký sản phẩm mới trong kỳ, có ghi nhận SA là người giới thiệu",
        "sort_order": 27,
    },
    {
        "metric_code": "B4_28",
        "definition_code": "SALE_GROUP_CONVERSION_RATE",
        "group_code": "B4",
        "metric_name": "Tỷ lệ chuyển đổi nhóm KH",
        "kpi_type": "SALE_CSKH",
        "input_type": "AUTO",
        "formula_key": "sale_group_conversion_rate",
        "unit": "PERCENT",
        "weight_percent": "3.00",
        "target_value": "5.00",
        "target_text": "≥5% tỷ lệ chuyển đổi / quý",
        "frequency": "Quý",
        "work_description": "KH nhóm Nuôi dưỡng / Không nghe máy được nâng lên nhóm Tiềm năng hoặc Rất tiềm năng dựa trên phản hồi thực tế.",
        "measurement_formula": "CRM: (Số KH chuyển lên nhóm TP/RTP / Tổng KH nhóm thấp được gọi lại trong kỳ) × 100%",
        "sort_order": 28,
    },
]


DEFAULT_REWARD_TIERS = [
    {
        "tier_code": "GOLD",
        "tier_name": "Vàng - PHÍ KÍCH HOẠT",
        "description": "Top 3 theo phí giao dịch phát sinh và đạt tất cả điều kiện cổng.",
        "rank_metric_code": "TOTAL_FEE",
        "rank_limit": 3,
        "min_total_score": None,
        "require_all_gates_passed": True,
        "reward_type": "CASH",
        "sort_order": 1,
    },
    {
        "tier_code": "SILVER",
        "tier_name": "Bạc - TK KÍCH HOẠT",
        "description": "Top 3 theo số tài khoản tái kích hoạt và đạt tất cả điều kiện cổng.",
        "rank_metric_code": "REACTIVATED_ACCOUNTS",
        "rank_limit": 3,
        "min_total_score": None,
        "require_all_gates_passed": True,
        "reward_type": "CASH",
        "sort_order": 2,
    },
    {
        "tier_code": "STANDARD",
        "tier_name": "Đạt chuẩn",
        "description": "Đạt chuẩn KPI và đạt tất cả điều kiện cổng.",
        "rank_metric_code": None,
        "rank_limit": None,
        "min_total_score": Decimal("70.00"),
        "require_all_gates_passed": True,
        "reward_type": "RECOGNITION",
        "sort_order": 3,
    },
    {
        "tier_code": "FAILED",
        "tier_name": "Chưa đạt",
        "description": "Không đạt điều kiện cổng hoặc tổng điểm dưới ngưỡng.",
        "rank_metric_code": None,
        "rank_limit": None,
        "min_total_score": None,
        "require_all_gates_passed": False,
        "reward_type": "IMPROVEMENT_PLAN",
        "sort_order": 4,
    },
]

DEFAULT_METRIC_DEFINITIONS = [
    {
        "metric_code": item["definition_code"],
        "metric_name": item["metric_name"],
        "description": item["work_description"],
        "input_type": item["input_type"],
        "formula_key": item["formula_key"],
        "unit": item["unit"],
        "is_active": True,
    }
    for item in DEFAULT_KPI_PERIOD_METRICS
]