# Generated by Django 6.0.6 on 2026-07-03 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('tickets', '0002_ticket_sla_policy_ticketupdatelog_new_sla_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('call_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recording_url', models.TextField(blank=True, null=True)),
                ('recording_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_system', models.CharField(blank=True, max_length=50, null=True)),
                ('external_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='branches.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customers.customer')),
                ('customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customers.customeraccount')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='branches.employee')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'call_logs',
            },
        ),
        migrations.CreateModel(
            name='CallAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_access_logs', to=settings.AUTH_USER_MODEL)),
                ('call_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='calls.calllog')),
            ],
            options={
                'db_table': 'call_access_logs',
            },
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['ticket'], name='call_logs_ticket__b18e79_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['customer'], name='call_logs_custome_41ca8a_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['employee'], name='call_logs_employe_12e83f_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['branch'], name='call_logs_branch__913b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['call_time'], name='call_logs_call_ti_26cba0_idx'),
        ),
        migrations.AddIndex(
            model_name='callaccesslog',
            index=models.Index(fields=['call_log'], name='call_access_call_lo_34e464_idx'),
        ),
        migrations.AddIndex(
            model_name='callaccesslog',
            index=models.Index(fields=['user'], name='call_access_user_id_c4ae57_idx'),
        ),
        migrations.AddIndex(
            model_name='callaccesslog',
            index=models.Index(fields=['action_type'], name='call_access_action__13e204_idx'),
        ),
        migrations.AddIndex(
            model_name='callaccesslog',
            index=models.Index(fields=['accessed_at'], name='call_access_accesse_3c8e70_idx'),
        ),
    ]
