# Generated by Django 6.0.6 on 2026-07-03 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaBreachReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('reason_code', models.CharField(max_length=50, unique=True)),
                ('reason_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sla_breach_reasons',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sla_code', models.CharField(max_length=50, unique=True)),
                ('sla_name', models.CharField(max_length=255)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
                ('assignment_time_minutes', models.IntegerField(blank=True, null=True)),
                ('processing_time_minutes', models.IntegerField(blank=True, null=True)),
                ('resolution_time_minutes', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_sla_policies', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='branches.branch')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='tickets.ticketclassification')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sla_policies', to=settings.AUTH_USER_MODEL)),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='customers.customertype')),
                ('parent_sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='sla.slapolicy')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='tickets.ticketpriority')),
                ('processing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='branches.processingunit')),
                ('support_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='tickets.ticketsupportcategory')),
            ],
            options={
                'db_table': 'sla_policies',
            },
        ),
        migrations.CreateModel(
            name='SlaEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rule_code', models.CharField(max_length=50, unique=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_after_minutes', models.IntegerField(default=0)),
                ('repeat_interval_minutes', models.IntegerField(blank=True, null=True)),
                ('recipient_type', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='sla.slapolicy')),
            ],
            options={
                'db_table': 'sla_escalation_rules',
            },
        ),
        migrations.CreateModel(
            name='SlaPolicyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('branch_resolve_type', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_minutes', models.IntegerField(blank=True, null=True)),
                ('is_sla_counted', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policy_tasks', to='branches.branch')),
                ('processing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policy_tasks', to='branches.processingunit')),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_tasks', to='sla.slapolicy')),
            ],
            options={
                'db_table': 'sla_policy_tasks',
            },
        ),
        migrations.CreateModel(
            name='SlaPolicyTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(default='FINISH_TO_START', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('depends_on_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_sources', to='sla.slapolicytask')),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='sla.slapolicy')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_targets', to='sla.slapolicytask')),
            ],
            options={
                'db_table': 'sla_policy_task_dependencies',
            },
        ),
        migrations.CreateModel(
            name='TicketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_alerts',
            },
        ),
        migrations.CreateModel(
            name='TicketDepartmentSlaTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('total_standard_minutes', models.IntegerField(blank=True, null=True)),
                ('total_actual_minutes', models.IntegerField(blank=True, null=True)),
                ('task_count', models.IntegerField(default=0)),
                ('completed_task_count', models.IntegerField(default=0)),
                ('overdue_task_count', models.IntegerField(default=0)),
                ('sla_status', models.CharField(blank=True, max_length=30, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_sla_trackings', to='branches.branch')),
                ('processing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_sla_trackings', to='branches.processingunit')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_sla_trackings', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_department_sla_tracking',
            },
        ),
        migrations.CreateModel(
            name='TicketSlaTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_due_at', models.DateTimeField(blank=True, null=True)),
                ('processing_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('standard_response_minutes', models.IntegerField(blank=True, null=True)),
                ('standard_assignment_minutes', models.IntegerField(blank=True, null=True)),
                ('standard_processing_minutes', models.IntegerField(blank=True, null=True)),
                ('standard_resolution_minutes', models.IntegerField(blank=True, null=True)),
                ('waiting_assignment_minutes', models.IntegerField(blank=True, null=True)),
                ('waiting_processing_minutes', models.IntegerField(blank=True, null=True)),
                ('processing_minutes', models.IntegerField(blank=True, null=True)),
                ('total_minutes', models.IntegerField(blank=True, null=True)),
                ('sla_status', models.CharField(blank=True, max_length=30, null=True)),
                ('breach_note', models.TextField(blank=True, null=True)),
                ('breach_reason_submitted', models.BooleanField(default=False)),
                ('breach_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_sla_trackings', to='sla.slabreachreason')),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_trackings', to='sla.slapolicy')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_sla_tracking',
            },
        ),
        migrations.CreateModel(
            name='TicketSlaReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_reminders', to='sla.slaescalationrule')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_reminders', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_reminders', to='tickets.ticket')),
                ('sla_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='sla.ticketslatracking')),
            ],
            options={
                'db_table': 'ticket_sla_reminders',
            },
        ),
        migrations.CreateModel(
            name='TicketTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_status', models.CharField(default='PENDING', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('is_sla_counted', models.BooleanField(default=True)),
                ('standard_minutes', models.IntegerField(blank=True, null=True)),
                ('actual_minutes', models.IntegerField(blank=True, null=True)),
                ('sla_status', models.CharField(blank=True, max_length=30, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_tasks', to='branches.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_tasks', to='branches.branch')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ticket_tasks', to=settings.AUTH_USER_MODEL)),
                ('processing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_tasks', to='branches.processingunit')),
                ('sla_policy_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_tasks', to='sla.slapolicytask')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_tasks',
            },
        ),
        migrations.CreateModel(
            name='TicketTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(default='FINISH_TO_START', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('depends_on_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_sources', to='sla.tickettask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_targets', to='sla.tickettask')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_task_dependencies',
            },
        ),
        migrations.CreateModel(
            name='TicketTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=50, null=True)),
                ('to_status', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_task_logs', to=settings.AUTH_USER_MODEL)),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_task_logs_from', to='branches.employee')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to='tickets.ticket')),
                ('ticket_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sla.tickettask')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_task_logs_to', to='branches.employee')),
            ],
            options={
                'db_table': 'ticket_task_logs',
            },
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['support_category'], name='sla_policie_support_ff503e_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['classification'], name='sla_policie_classif_2851be_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['priority'], name='sla_policie_priorit_a55561_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['processing_unit'], name='sla_policie_process_0efbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['branch'], name='sla_policie_branch__f787c6_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['customer_type'], name='sla_policie_custome_30d0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['status'], name='sla_policie_status_1ccb32_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['is_active'], name='sla_policie_is_acti_5f1121_idx'),
        ),
        migrations.AddIndex(
            model_name='slaescalationrule',
            index=models.Index(fields=['sla_policy'], name='sla_escalat_sla_pol_376abe_idx'),
        ),
        migrations.AddIndex(
            model_name='slaescalationrule',
            index=models.Index(fields=['trigger_type'], name='sla_escalat_trigger_6c403a_idx'),
        ),
        migrations.AddIndex(
            model_name='slaescalationrule',
            index=models.Index(fields=['recipient_type'], name='sla_escalat_recipie_69a5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='slaescalationrule',
            index=models.Index(fields=['is_active'], name='sla_escalat_is_acti_4c9521_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytask',
            index=models.Index(fields=['sla_policy'], name='sla_policy__sla_pol_71ccfe_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytask',
            index=models.Index(fields=['processing_unit'], name='sla_policy__process_bc0da2_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytask',
            index=models.Index(fields=['default_branch'], name='sla_policy__default_22dbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytask',
            index=models.Index(fields=['sort_order'], name='sla_policy__sort_or_7c1ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytask',
            index=models.Index(fields=['is_active'], name='sla_policy__is_acti_65bcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytaskdependency',
            index=models.Index(fields=['sla_policy'], name='sla_policy__sla_pol_a66c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytaskdependency',
            index=models.Index(fields=['task'], name='sla_policy__task_id_1b1010_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytaskdependency',
            index=models.Index(fields=['depends_on_task'], name='sla_policy__depends_df211f_idx'),
        ),
        migrations.AddConstraint(
            model_name='slapolicytaskdependency',
            constraint=models.UniqueConstraint(fields=('sla_policy', 'task', 'depends_on_task'), name='uq_sla_policy_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='slapolicytaskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on_task')), _negated=True), name='ck_sla_policy_task_not_self_dependent'),
        ),
        migrations.AddIndex(
            model_name='ticketalert',
            index=models.Index(fields=['ticket'], name='ticket_aler_ticket__7f0058_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketalert',
            index=models.Index(fields=['alert_type'], name='ticket_aler_alert_t_d96f55_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketalert',
            index=models.Index(fields=['status'], name='ticket_aler_status_7e8770_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketalert',
            index=models.Index(fields=['triggered_at'], name='ticket_aler_trigger_5a05db_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdepartmentslatracking',
            index=models.Index(fields=['ticket'], name='ticket_depa_ticket__fa3471_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdepartmentslatracking',
            index=models.Index(fields=['processing_unit'], name='ticket_depa_process_8ae8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdepartmentslatracking',
            index=models.Index(fields=['branch'], name='ticket_depa_branch__a3736e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdepartmentslatracking',
            index=models.Index(fields=['sla_status'], name='ticket_depa_sla_sta_c47402_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketdepartmentslatracking',
            constraint=models.UniqueConstraint(fields=('ticket', 'processing_unit', 'branch'), name='uq_ticket_department_sla_tracking'),
        ),
        migrations.AddIndex(
            model_name='ticketslatracking',
            index=models.Index(fields=['sla_policy'], name='ticket_sla__sla_pol_9ec0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketslatracking',
            index=models.Index(fields=['sla_status'], name='ticket_sla__sla_sta_9cb630_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketslatracking',
            index=models.Index(fields=['resolution_due_at'], name='ticket_sla__resolut_23bacb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketslatracking',
            index=models.Index(fields=['breached_at'], name='ticket_sla__breache_915f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketslareminder',
            index=models.Index(fields=['ticket'], name='ticket_sla__ticket__08b1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketslareminder',
            index=models.Index(fields=['escalation_rule'], name='ticket_sla__escalat_80f717_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketslareminder',
            index=models.Index(fields=['recipient_user'], name='ticket_sla__recipie_ab9e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketslareminder',
            index=models.Index(fields=['sent_at'], name='ticket_sla__sent_at_6d7824_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettask',
            index=models.Index(fields=['ticket'], name='ticket_task_ticket__b3c20c_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettask',
            index=models.Index(fields=['processing_unit'], name='ticket_task_process_5deb79_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettask',
            index=models.Index(fields=['branch'], name='ticket_task_branch__f81135_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettask',
            index=models.Index(fields=['assigned_employee'], name='ticket_task_assigne_2cd69b_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettask',
            index=models.Index(fields=['task_status'], name='ticket_task_task_st_08fc74_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettask',
            index=models.Index(fields=['sla_status'], name='ticket_task_sla_sta_d849c6_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettaskdependency',
            index=models.Index(fields=['ticket'], name='ticket_task_ticket__9a5d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettaskdependency',
            index=models.Index(fields=['task'], name='ticket_task_task_id_2eb276_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettaskdependency',
            index=models.Index(fields=['depends_on_task'], name='ticket_task_depends_0dd3f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='tickettaskdependency',
            constraint=models.UniqueConstraint(fields=('ticket', 'task', 'depends_on_task'), name='uq_ticket_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='tickettaskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on_task')), _negated=True), name='ck_ticket_task_not_self_dependent'),
        ),
        migrations.AddIndex(
            model_name='tickettasklog',
            index=models.Index(fields=['ticket'], name='ticket_task_ticket__63a1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettasklog',
            index=models.Index(fields=['ticket_task'], name='ticket_task_ticket__684b73_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettasklog',
            index=models.Index(fields=['action_type'], name='ticket_task_action__bd10de_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettasklog',
            index=models.Index(fields=['created_at'], name='ticket_task_created_a1ce8b_idx'),
        ),
    ]
