# Generated by Django 6.0.6 on 2026-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0002_slapolicy_assigned_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slapolicy',
            name='sla_code',
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
