# Generated by Django 5.2.16 on 2026-07-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0002_alter_slabreachreason_id_alter_slaescalationrule_id_and_more'),
        ('sla', '0003_remove_slapolicy_sla_code_slapolicy_description'),
    ]

    operations = [
    ]
