# Generated by Django 6.0.6 on 2026-07-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0004_merge_20260710_0124'),
        ('sla', '0004_merge_20260710_0803'),
    ]

    operations = [
    ]
