# Generated by Django 6.0.6 on 2026-07-24 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_employeeorganizationmembership_organizationunit_and_more'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('sla', '0006_ticket_account_link_status_and_code_rule'),
        ('tickets', '0012_optimize_dashboard_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrganizationUnitSlaTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('total_standard_minutes', models.IntegerField(blank=True, null=True)),
                ('total_actual_minutes', models.IntegerField(blank=True, null=True)),
                ('task_count', models.IntegerField(default=0)),
                ('completed_task_count', models.IntegerField(default=0)),
                ('overdue_task_count', models.IntegerField(default=0)),
                ('sla_status', models.CharField(blank=True, max_length=30, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_organization_unit_sla_tracking',
            },
        ),
        migrations.RemoveIndex(
            model_name='ticketdepartmentslatracking',
            name='ticket_depa_ticket__fa3471_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketdepartmentslatracking',
            name='ticket_depa_process_8ae8e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketdepartmentslatracking',
            name='ticket_depa_branch__a3736e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketdepartmentslatracking',
            name='ticket_depa_sla_sta_c47402_idx',
        ),
        migrations.RemoveConstraint(
            model_name='ticketdepartmentslatracking',
            name='uq_ticket_department_sla_tracking',
        ),
        migrations.RemoveIndex(
            model_name='slapolicy',
            name='sla_policie_process_0efbdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='slapolicytask',
            name='sla_policy__process_bc0da2_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettask',
            name='ticket_task_process_5deb79_idx',
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policies', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='slapolicytask',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_policy_tasks', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='tickettask',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_tasks', to='branches.organizationunit'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['organization_unit'], name='sla_policie_organiz_5f2238_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicytask',
            index=models.Index(fields=['organization_unit'], name='sla_policy__organiz_d45dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettask',
            index=models.Index(fields=['organization_unit'], name='ticket_task_organiz_b49383_idx'),
        ),
        migrations.AddField(
            model_name='ticketorganizationunitslatracking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_unit_sla_trackings', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='ticketorganizationunitslatracking',
            name='organization_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_unit_sla_trackings', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='ticketorganizationunitslatracking',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_unit_sla_trackings', to='tickets.ticket'),
        ),
        migrations.RemoveField(
            model_name='ticketdepartmentslatracking',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='ticketdepartmentslatracking',
            name='processing_unit',
        ),
        migrations.RemoveField(
            model_name='ticketdepartmentslatracking',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='slapolicy',
            name='processing_unit',
        ),
        migrations.RemoveField(
            model_name='slapolicytask',
            name='processing_unit',
        ),
        migrations.RemoveField(
            model_name='tickettask',
            name='processing_unit',
        ),
        migrations.AddIndex(
            model_name='ticketorganizationunitslatracking',
            index=models.Index(fields=['ticket'], name='ticket_orga_ticket__17adac_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorganizationunitslatracking',
            index=models.Index(fields=['organization_unit'], name='ticket_orga_organiz_1b2f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorganizationunitslatracking',
            index=models.Index(fields=['branch'], name='ticket_orga_branch__703806_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorganizationunitslatracking',
            index=models.Index(fields=['sla_status'], name='ticket_orga_sla_sta_334c0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketorganizationunitslatracking',
            constraint=models.UniqueConstraint(fields=('ticket', 'organization_unit', 'branch'), name='uq_ticket_organization_unit_sla_tracking'),
        ),
        migrations.DeleteModel(
            name='TicketDepartmentSlaTracking',
        ),
    ]
