# Generated by Django 6.0.6 on 2026-07-03 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('sla', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='sla.slapolicy'),
        ),
        migrations.AddField(
            model_name='ticketupdatelog',
            name='new_sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_update_logs_new', to='sla.slapolicy'),
        ),
        migrations.AddField(
            model_name='ticketupdatelog',
            name='old_sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_update_logs_old', to='sla.slapolicy'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_policy'], name='tickets_sla_pol_8a3796_idx'),
        ),
    ]
