# Generated by Django 6.0.6 on 2026-07-07 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0002_remove_customeraccount_uq_customer_account_number_and_more'),
        ('sla', '0001_initial'),
        ('tickets', '0002_ticket_sla_policy_ticketupdatelog_new_sla_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), ('source_ref_id__isnull', False), models.Q(('source_ref_id', ''), _negated=True)), fields=('source', 'source_ref_id'), name='uq_ticket_source_source_ref_id'),
        ),
    ]
