# Generated by Django 6.0.6 on 2026-07-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('tickets', '0005_ticket_error_master_and_fields'),
]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_error_g_1b8f01_idx',
            old_name='tickets_error_g_3f0e71_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_error_t_e7b221_idx',
            old_name='tickets_error_t_7e0e4b_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_error_c_984db4_idx',
            old_name='tickets_error_c_ad98b4_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_related_eba243_idx',
            old_name='tickets_related_9e97f5_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_externa_b06505_idx',
            old_name='tickets_external_945ce8_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorcontent',
            new_name='ticket_erro_error_t_4b0adc_idx',
            old_name='ticket_erro_error_t_611aa4_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorcontent',
            new_name='ticket_erro_content_cf54de_idx',
            old_name='ticket_erro_content_37f1cf_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorcontent',
            new_name='ticket_erro_content_fc883b_idx',
            old_name='ticket_erro_content_61d553_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorcontent',
            new_name='ticket_erro_is_acti_f6a228_idx',
            old_name='ticket_erro_is_acti_5c680d_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorgroup',
            new_name='ticket_erro_group_c_871be4_idx',
            old_name='ticket_erro_group_c_69c553_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorgroup',
            new_name='ticket_erro_group_n_eb04a8_idx',
            old_name='ticket_erro_group_n_d1fe32_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorgroup',
            new_name='ticket_erro_related_2edb7e_idx',
            old_name='ticket_erro_related_9f0c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrorgroup',
            new_name='ticket_erro_is_acti_9d59df_idx',
            old_name='ticket_erro_is_acti_f94a4b_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrortype',
            new_name='ticket_erro_group_i_6e310e_idx',
            old_name='ticket_erro_group_i_693d3a_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrortype',
            new_name='ticket_erro_type_co_06051a_idx',
            old_name='ticket_erro_type_co_8f5c42_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrortype',
            new_name='ticket_erro_type_na_b9cdcc_idx',
            old_name='ticket_erro_type_na_4bd350_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrortype',
            new_name='ticket_erro_related_5ab245_idx',
            old_name='ticket_erro_related_4b49bb_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketerrortype',
            new_name='ticket_erro_is_acti_74da2a_idx',
            old_name='ticket_erro_is_acti_0aa625_idx',
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketactivitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketclassification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketfeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketfollower',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketpriority',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketprocesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketsource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketsupportcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tickettag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketupdatelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
