# Generated by Django 6.0.6 on 2026-07-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_tickets_error_g_3f0e71_idx_tickets_error_g_1b8f01_idx_and_more'),
        ('tickets', '0007_remove_ticket_error_content'),
    ]

    operations = [
    ]
