# Generated by Django 6.0.6 on 2026-07-15 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('sla', '0006_ticket_account_link_status_and_code_rule'),
        ('tickets', '0008_merge_20260715_0252'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="ticket",
                    name="tickets_error_c_984db4_idx",
                ),
            ],
        ),

        migrations.AddField(
            model_name='ticket',
            name='account_link_status',
            field=models.CharField(choices=[('LINKED', 'Có TK liên kết'), ('UNLINKED', 'Chưa có TK liên kết')], db_index=True, default='UNLINKED', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='raw_account_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer_account'], name='tickets_custome_8f1d52_idx'),
        ),
    ]
