# Generated by Django 6.0.6 on 2026-07-22 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_seed_default_processing_units'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('sla', '0006_ticket_account_link_status_and_code_rule'),
        ('tickets', '0010_repair_raw_account_number_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at', 'current_status'], name='tkt_created_status_ix'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at', 'handling_branch'], name='tkt_created_branch_ix'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at', 'source'], name='tkt_created_source_ix'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at', 'support_category'], name='tkt_created_category_ix'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at', 'account_link_status'], name='tkt_created_link_ix'),
        ),
    ]
