# Generated by Django 6.0.6 on 2026-07-24 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_employeeorganizationmembership_organizationunit_and_more'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('sla', '0007_ticketorganizationunitslatracking_and_more'),
        ('tickets', '0012_optimize_dashboard_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketassignment',
            name='ticket_assi_to_unit_3e3d44_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_unit',
        ),
        migrations.RemoveField(
            model_name='ticketupdatelog',
            name='from_unit',
        ),
        migrations.RemoveField(
            model_name='ticketupdatelog',
            name='to_unit',
        ),
        migrations.AddField(
            model_name='ticket',
            name='handling_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_tickets', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='from_organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_from', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='to_organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_to', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='ticketupdatelog',
            name='from_organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_update_logs_from', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='ticketupdatelog',
            name='to_organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_update_logs_to', to='branches.organizationunit'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['handling_unit'], name='tickets_handlin_f4941d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['handling_unit', 'created_at'], name='tkt_unit_created_ix'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['to_organization_unit'], name='ticket_assi_to_orga_b4f2a0_idx'),
        ),
        migrations.RemoveField(
            model_name='ticketassignment',
            name='from_unit',
        ),
        migrations.RemoveField(
            model_name='ticketassignment',
            name='to_unit',
        ),
    ]
