# Generated by Django 6.0.6 on 2026-08-05 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('tickets', '0014_remove_pending_close_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfeedback',
            name='message_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketfeedback',
            name='message_template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketfeedback',
            name='message_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketfeedback',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketfeedback',
            name='ticket_ref_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TicketSurveyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('send_status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], db_index=True, max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(blank=True, max_length=100, null=True)),
                ('message_template', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_ref_text', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_score', models.IntegerField(blank=True, null=True)),
                ('rating_note', models.TextField(blank=True, null=True)),
                ('entry_source', models.CharField(choices=[('MANUAL', 'Nhập tay'), ('IMPORT', 'Import Excel')], default='MANUAL', max_length=20)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_survey_logs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_survey_logs', to='customers.customer')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tickets.ticketfeedback')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_survey_logs',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['ticket', 'send_status'], name='ticket_surv_ticket__8ff739_idx')],
            },
        ),
    ]
