# Generated by Django 6.0.6 on 2026-08-05 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_survey_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSurveyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Nhập mới'), ('UPDATE', 'Chỉnh sửa')], max_length=20)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_survey_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('survey_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticketsurveylog')),
            ],
            options={
                'db_table': 'ticket_survey_audit_logs',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
