class TicketStatusCode:
    CREATED = "CREATED"              # Mở (ban đầu khi tạo ticket)
    ACCEPTED = "ACCEPTED"            # Tiếp nhận
    PROCESSING = "PROCESSING"       # Đang xử lý
    DONE_WAIT_CLOSE = "DONE_WAIT_CLOSE"  # Đã xong (chờ đóng) — đếm 1h rồi tự đóng
    CLOSED = "CLOSED"               # Đã đóng (khóa, chỉ admin sửa)
    CANCELLED = "CANCELLED"         # Đã hủy — nằm ngoài vòng đời, không phải một bước

    # Nhãn hiển thị tiếng Việt.
    # Bỏ PENDING_CLOSE ("Chờ đóng"): việc chờ đóng đã nằm ngay trong
    # DONE_WAIT_CLOSE (đếm 1 tiếng rồi tự chuyển CLOSED) nên một trạng thái
    # trung gian riêng chỉ làm vòng đời dài thêm mà không mang thêm thông tin.
    LABELS = {
        CREATED: "Mở",
        ACCEPTED: "Tiếp nhận",
        PROCESSING: "Đang xử lý",
        DONE_WAIT_CLOSE: "Đã xong (chờ đóng)",
        CLOSED: "Đã đóng",
        CANCELLED: "Đã hủy",
    }


class TicketActionType:
    CREATE = "CREATE"
    AMEND = "AMEND"
    UPDATE_STATUS = "UPDATE_STATUS"
    ASSIGN_EMPLOYEE = "ASSIGN_EMPLOYEE"
    TRANSFER_ORGANIZATION_UNIT = "TRANSFER_ORGANIZATION_UNIT"
    # Alias tương thích với log cũ.
    TRANSFER_UNIT = TRANSFER_ORGANIZATION_UNIT
    TRANSFER_BRANCH = "TRANSFER_BRANCH"
    CLOSE = "CLOSE"
    CANCEL = "CANCEL"


class ClassificationMethod:
    AUTO = "AUTO"
    MANUAL = "MANUAL"


class NotificationType:
    ASSIGNED_TICKET = "ASSIGNED_TICKET"
    SLA_OVERDUE = "SLA_OVERDUE"
    SLA_OVERDUE_72H = "SLA_OVERDUE_72H"
    STATUS_UPDATED = "STATUS_UPDATED"


class TaskStatus:
    PENDING = "PENDING"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class SlaStatus:
    PROCESSING = "PROCESSING"
    ON_TIME = "ON_TIME"
    OVERDUE = "OVERDUE"


class PermissionCode:


    SA_RECORD_VIEW = "SA_RECORD_VIEW"
    SA_RECORD_CREATE = "SA_RECORD_CREATE"
    SA_RECORD_UPDATE = "SA_RECORD_UPDATE"
    SA_RECORD_DELETE = "SA_RECORD_DELETE"
    SA_RECORD_IMPORT = "SA_RECORD_IMPORT"
    SA_RECORD_AUDIT_VIEW = "SA_RECORD_AUDIT_VIEW"

    SA_KPI_VIEW_SELF = "SA_KPI_VIEW_SELF"
    SA_KPI_VIEW_BRANCH = "SA_KPI_VIEW_BRANCH"
    SA_KPI_CONFIG = "SA_KPI_CONFIG"
    SA_DASHBOARD_VIEW = "SA_DASHBOARD_VIEW"

    CUSTOMER_360_VIEW = "CUSTOMER_360_VIEW"

    TICKET_CREATE = "TICKET_CREATE"
    TICKET_AMEND = "TICKET_AMEND"
    TICKET_UPDATE_STATUS = "TICKET_UPDATE_STATUS"
    TICKET_ASSIGN = "TICKET_ASSIGN"
    TICKET_VIEW = "TICKET_VIEW"
    TICKET_ERROR_REPORT_VIEW = "TICKET_ERROR_REPORT_VIEW"
    TICKET_ERROR_REPORT_EXPORT = "TICKET_ERROR_REPORT_EXPORT"
    TICKET_ERROR_MASTER_MANAGE = "TICKET_ERROR_MASTER_MANAGE"

    SLA_CREATE = "SLA_CREATE"
    SLA_AMEND = "SLA_AMEND"
    SLA_ACTIVATE_DEACTIVATE = "SLA_ACTIVATE_DEACTIVATE"
    SLA_VIEW = "SLA_VIEW"

    OVERDUE_SLA_NOTIFICATION = "OVERDUE_SLA_NOTIFICATION"
    OVERDUE_SLA_EMAIL = "OVERDUE_SLA_EMAIL"

    CALL_HISTORY_VIEW = "CALL_HISTORY_VIEW"
    CALL_HISTORY_LISTEN = "CALL_HISTORY_LISTEN"

    CUSTOMER_CREATE = "CUSTOMER_CREATE"
    CUSTOMER_AMEND = "CUSTOMER_AMEND"

    AUTO_REPORT_VIEW = "AUTO_REPORT_VIEW"
    AUTO_REPORT_EXPORT = "AUTO_REPORT_EXPORT"
    CUSTOM_REPORT_VIEW = "CUSTOM_REPORT_VIEW"
    CUSTOM_REPORT_EXPORT = "CUSTOM_REPORT_EXPORT"


class RoleCode:
    CS_STAFF = "CS_STAFF"
    CS_SUPERVISOR = "CS_SUPERVISOR"
    CS_MANAGER = "CS_MANAGER"
    RELATED_DEPT = "RELATED_DEPT"
    IC = "IC"
    BOM = "BOM"

    SA_STAFF = "SA_STAFF"
    SA_SUPERVISOR = "SA_SUPERVISOR"
    SA_MANAGER = "SA_MANAGER"
    SA_ADMIN = "SA_ADMIN"

    CCC_STAFF = "CCC_STAFF"
    CCC_SUPERVISOR = "CCC_SUPERVISOR"
    CCC_MANAGER = "CCC_MANAGER"

    SYSTEM_ADMIN = "SYSTEM_ADMIN"


class ScopeType:
    OWN = "OWN"
    ORGANIZATION_UNIT = "ORGANIZATION_UNIT"
    BRANCH = "BRANCH"
    MULTI_BRANCH = "MULTI_BRANCH"
    ALL = "ALL"