class TicketStatusCode:
    CREATED = "CREATED"
    ACCEPTED = "ACCEPTED"
    PROCESSING = "PROCESSING"
    DONE_WAIT_CLOSE = "DONE_WAIT_CLOSE"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class TicketActionType:
    CREATE = "CREATE"
    AMEND = "AMEND"
    UPDATE_STATUS = "UPDATE_STATUS"
    ASSIGN_EMPLOYEE = "ASSIGN_EMPLOYEE"
    TRANSFER_UNIT = "TRANSFER_UNIT"
    TRANSFER_BRANCH = "TRANSFER_BRANCH"
    CLOSE = "CLOSE"
    CANCEL = "CANCEL"


class ClassificationMethod:
    AUTO = "AUTO"
    MANUAL = "MANUAL"


class NotificationType:
    ASSIGNED_TICKET = "ASSIGNED_TICKET"
    SLA_OVERDUE = "SLA_OVERDUE"
    SLA_OVERDUE_72H = "SLA_OVERDUE_72H"
    STATUS_UPDATED = "STATUS_UPDATED"


class TaskStatus:
    PENDING = "PENDING"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"


class SlaStatus:
    PROCESSING = "PROCESSING"
    ON_TIME = "ON_TIME"
    OVERDUE = "OVERDUE"


class PermissionCode:
    TICKET_CREATE = "TICKET_CREATE"
    TICKET_AMEND = "TICKET_AMEND"
    TICKET_UPDATE_STATUS = "TICKET_UPDATE_STATUS"
    TICKET_ASSIGN = "TICKET_ASSIGN"
    TICKET_VIEW = "TICKET_VIEW"

    SLA_CREATE = "SLA_CREATE"
    SLA_AMEND = "SLA_AMEND"
    SLA_ACTIVATE_DEACTIVATE = "SLA_ACTIVATE_DEACTIVATE"
    SLA_VIEW = "SLA_VIEW"

    OVERDUE_SLA_NOTIFICATION = "OVERDUE_SLA_NOTIFICATION"
    OVERDUE_SLA_EMAIL = "OVERDUE_SLA_EMAIL"

    CALL_HISTORY_VIEW = "CALL_HISTORY_VIEW"
    CALL_HISTORY_LISTEN = "CALL_HISTORY_LISTEN"

    CUSTOMER_CREATE = "CUSTOMER_CREATE"
    CUSTOMER_AMEND = "CUSTOMER_AMEND"

    AUTO_REPORT_VIEW = "AUTO_REPORT_VIEW"
    AUTO_REPORT_EXPORT = "AUTO_REPORT_EXPORT"
    CUSTOM_REPORT_VIEW = "CUSTOM_REPORT_VIEW"
    CUSTOM_REPORT_EXPORT = "CUSTOM_REPORT_EXPORT"


class RoleCode:
    CS_STAFF = "CS_STAFF"
    CS_SUPERVISOR = "CS_SUPERVISOR"
    CS_MANAGER = "CS_MANAGER"
    RELATED_DEPT = "RELATED_DEPT"
    IC = "IC"
    BOM = "BOM"


class ScopeType:
    OWN = "OWN"
    BRANCH = "BRANCH"
    MULTI_BRANCH = "MULTI_BRANCH"
    ALL = "ALL"