# Generated by Django 6.0.6 on 2026-08-05 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EkycRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(db_index=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('call_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('follow_count', models.PositiveIntegerField(default=1)),
                ('call_status', models.CharField(choices=[('Nghe máy', 'Nghe máy'), ('Không nghe máy', 'Không nghe máy'), ('Thuê bao không tồn tại', 'Thuê bao không tồn tại')], db_index=True, default='Nghe máy', max_length=50)),
                ('call_result', models.CharField(choices=[('Khách hàng tắt máy ngang', 'Khách hàng tắt máy ngang'), ('KH không bấm phím', 'KH không bấm phím'), ('Khách hàng bấm phím', 'Khách hàng bấm phím')], db_index=True, default='Khách hàng bấm phím', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ekyc_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ekyc_records', to='customers.customer')),
                ('customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ekyc_records', to='customers.customeraccount')),
            ],
            options={
                'db_table': 'ekyc_records',
                'ordering': ['-call_date', '-id'],
                'indexes': [models.Index(fields=['account_number'], name='ekyc_record_account_d4686f_idx'), models.Index(fields=['call_date'], name='ekyc_record_call_da_44160f_idx'), models.Index(fields=['call_status'], name='ekyc_record_call_st_12270d_idx'), models.Index(fields=['call_result'], name='ekyc_record_call_re_edce4a_idx')],
            },
        ),
    ]
