# Generated by Django 6.0.6 on 2026-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekycrecord',
            name='call_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ekycrecord',
            name='call_result',
            field=models.CharField(blank=True, choices=[('Khách hàng tắt máy ngang', 'Khách hàng tắt máy ngang'), ('KH không bấm phím', 'KH không bấm phím'), ('Khách hàng bấm phím', 'Khách hàng bấm phím')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ekycrecord',
            name='call_status',
            field=models.CharField(blank=True, choices=[('Nghe máy', 'Nghe máy'), ('Không nghe máy', 'Không nghe máy'), ('Thuê bao không tồn tại', 'Thuê bao không tồn tại')], db_index=True, max_length=50, null=True),
        ),
    ]
