# Generated by Django 6.0.6 on 2026-08-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekyc', '0002_alter_ekycrecord_call_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekycrecord',
            name='pic',
            field=models.CharField(blank=True, db_index=True, help_text='Ví dụ: autocall, không gọi, ...', max_length=100, null=True, verbose_name='PIC (loại gọi)'),
        ),
    ]
