from django.urls import path

from apps.chatbots.views import (
    ChatbotDashboardFAQAPIView,
    ChatbotDashboardOverviewAPIView,
    ChatbotDashboardTicketsAPIView,
    ChatbotSessionDetailAPIView,
    TicketChatbotChangeStatusAPIView,
    TicketChatbotClaimAPIView,
    TicketChatbotDetailAPIView,
    TicketChatbotHistoryAPIView,
    TicketChatbotListAPIView,
    TicketChatbotOptionsAPIView,
)

urlpatterns = [
    path(
        "dashboard/overview/",
        ChatbotDashboardOverviewAPIView.as_view(),
        name="chatbot-dashboard-overview",
    ),
    path(
        "dashboard/tickets/",
        ChatbotDashboardTicketsAPIView.as_view(),
        name="chatbot-dashboard-tickets",
    ),
    path(
        "dashboard/faqs/",
        ChatbotDashboardFAQAPIView.as_view(),
        name="chatbot-dashboard-faqs",
    ),
    path(
        "dashboard/sessions/<str:session_id>/",
        ChatbotSessionDetailAPIView.as_view(),
        name="chatbot-session-detail",
    ),
    path(
        "ticket-chatbots/",
        TicketChatbotListAPIView.as_view(),
        name="ticket-chatbot-list",
    ),
    path(
        "ticket-chatbots/options/",
        TicketChatbotOptionsAPIView.as_view(),
        name="ticket-chatbot-options",
    ),
    path(
        "ticket-chatbots/<int:pk>/",
        TicketChatbotDetailAPIView.as_view(),
        name="ticket-chatbot-detail",
    ),
    path(
        "ticket-chatbots/<int:pk>/history/",
        TicketChatbotHistoryAPIView.as_view(),
        name="ticket-chatbot-history",
    ),
    path(
        "ticket-chatbots/<int:pk>/claim/",
        TicketChatbotClaimAPIView.as_view(),
        name="ticket-chatbot-claim",
    ),
    path(
        "ticket-chatbots/<int:pk>/change-status/",
        TicketChatbotChangeStatusAPIView.as_view(),
        name="ticket-chatbot-change-status",
    ),
]
