# Generated by Django 6.0.6 on 2026-07-16 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalErrorDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('BAR', 'Biểu đồ cột'), ('LINE', 'Biểu đồ đường'), ('DONUT', 'Biểu đồ donut'), ('STACKED_BAR', 'Biểu đồ cột chồng'), ('STACKED_HORIZONTAL_BAR', 'Biểu đồ thanh ngang chồng'), ('TABLE', 'Bảng')], max_length=50)),
                ('group_by', models.CharField(max_length=50)),
                ('breakdown_by', models.CharField(blank=True, max_length=50, null=True)),
                ('metric', models.CharField(default='count', max_length=50)),
                ('sort_by', models.CharField(default='count', max_length=50)),
                ('sort_direction', models.CharField(default='desc', max_length=10)),
                ('limit', models.PositiveIntegerField(default=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_error_dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_error_dashboard_widgets',
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalErrorImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(choices=[('EXCEL', 'Excel'), ('API', 'API'), ('MANUAL', 'Nhập tay')], default='EXCEL', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('classified_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IMPORTED', 'Đã import'), ('CLASSIFYING', 'Đang phân loại'), ('CLASSIFIED', 'Đã phân loại'), ('FAILED', 'Lỗi')], db_index=True, default='IMPORTED', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_error_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_error_import_batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalErrorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, db_index=True, null=True)),
                ('completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('raw_source', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_device', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_result', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('raw_cause', models.TextField(blank=True, null=True)),
                ('raw_solution', models.TextField(blank=True, null=True)),
                ('clean_source', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('clean_device', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('clean_result', models.CharField(blank=True, max_length=255, null=True)),
                ('clean_content', models.TextField(blank=True, null=True)),
                ('clean_cause', models.TextField(blank=True, null=True)),
                ('clean_solution', models.TextField(blank=True, null=True)),
                ('error_type_code', models.CharField(blank=True, choices=[('ORDER', 'Lệnh Đặt'), ('LOGIN', 'Đăng Nhập'), ('DISPLAY', 'Hiển Thị'), ('EKYC_ACCOUNT', 'eKYC / Tài Khoản'), ('PORTAL_SYSTEM', 'Portal / Hệ Thống'), ('TRANSFER_PAYMENT', 'Chuyển Khoản / Thanh Toán'), ('COMPLAINT', 'Khiếu Nại'), ('SPECIAL', 'Đặc Biệt')], db_index=True, max_length=50, null=True)),
                ('error_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('normalized_issue', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('need_review', models.BooleanField(db_index=True, default=False)),
                ('classification_status', models.CharField(choices=[('UNCLASSIFIED', 'Chưa phân loại'), ('CLASSIFIED', 'Đã phân loại'), ('NEED_REVIEW', 'Cần kiểm tra'), ('CONFIRMED', 'Đã xác nhận'), ('FAILED', 'Lỗi phân loại')], db_index=True, default='UNCLASSIFIED', max_length=30)),
                ('classification_error', models.TextField(blank=True, null=True)),
                ('llm_model_id', models.CharField(blank=True, max_length=255, null=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='external_errors.externalerrorimportbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_error_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_external_error_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_error_records',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalErrorClassificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_logs', to='external_errors.externalerrorrecord')),
            ],
            options={
                'db_table': 'external_error_classification_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['received_date', 'error_type_code'], name='external_er_receive_33edde_idx'),
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['received_date', 'clean_device'], name='external_er_receive_4e6441_idx'),
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['received_date', 'clean_source'], name='external_er_receive_686440_idx'),
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['classification_status', 'need_review'], name='external_er_classif_70e305_idx'),
        ),
    ]
