# Generated by Django 6.0.6 on 2026-07-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_errors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('error_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'external_error_codes',
                'ordering': ['group__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalErrorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('group_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'external_error_groups',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='externalerrorrecord',
            name='external_er_receive_33edde_idx',
        ),
        migrations.AddField(
            model_name='externalerrorrecord',
            name='error_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='external_errors.externalerrorcode'),
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['received_date', 'error_code'], name='external_er_receive_9b60bd_idx'),
        ),
        migrations.AddField(
            model_name='externalerrorcode',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='error_codes', to='external_errors.externalerrorgroup'),
        ),
        migrations.RemoveField(
            model_name='externalerrorrecord',
            name='error_type_code',
        ),
        migrations.RemoveField(
            model_name='externalerrorrecord',
            name='error_type_name',
        ),
        migrations.AddIndex(
            model_name='externalerrorcode',
            index=models.Index(fields=['group', 'is_active'], name='external_er_group_i_e4d4fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalerrorcode',
            constraint=models.UniqueConstraint(fields=('group', 'error_name'), name='uniq_external_error_code_name_in_group'),
        ),
    ]
