# Generated by Django 6.0.6 on 2026-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_errors', '0002_externalerrorcode_externalerrorgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalerrorrecord',
            name='completed_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalerrorrecord',
            name='received_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
