# Generated by Django 6.0.6 on 2026-07-22 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_errors', '0004_externalerrorcausegroup_and_cause_classification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['received_date', 'classification_status'], name='ext_err_recv_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['received_date', 'cause_classification_status'], name='ext_err_recv_cstat_idx'),
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['completed_date', 'classification_status'], name='ext_err_done_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='externalerrorrecord',
            index=models.Index(fields=['completed_date', 'cause_classification_status'], name='ext_err_done_cstat_idx'),
        ),
    ]
