# Generated by Django 6.0.6 on 2026-07-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_ticket_sla_policy_ticketupdatelog_new_sla_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_chat_logs',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_cha_session_418751_idx'), models.Index(fields=['category'], name='chatbot_cha_categor_3fc160_idx'), models.Index(fields=['external_created_at'], name='chatbot_cha_externa_05536a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotCskhRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_cskh_requests',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_csk_session_10e16f_idx'), models.Index(fields=['status'], name='chatbot_csk_status_da6833_idx'), models.Index(fields=['external_created_at'], name='chatbot_csk_externa_fe487a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('step', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_states',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_sta_session_187a3b_idx'), models.Index(fields=['state'], name='chatbot_sta_state_517628_idx'), models.Index(fields=['external_created_at'], name='chatbot_sta_externa_b93c51_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('main_category', models.CharField(blank=True, max_length=100, null=True)),
                ('dashboard_category', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('outcome_type', models.CharField(choices=[('BOT_DONE', 'Đã đóng — Chatbot'), ('CCC', 'Đang xử lý — CCC'), ('SPAM', 'Câu hỏi rác'), ('TIMEOUT', 'Timeout'), ('WAITING_INFO', 'Đang chờ thông tin'), ('COLLECTED', 'Đã thu thập thông tin')], db_index=True, max_length=50)),
                ('has_cskh_request', models.BooleanField(default=False)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('first_question', models.TextField(blank=True, null=True)),
                ('last_question', models.TextField(blank=True, null=True)),
                ('full_conversation', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to='tickets.ticket')),
            ],
            options={
                'db_table': 'chatbot_session_summaries',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_ses_session_faec20_idx'), models.Index(fields=['main_category'], name='chatbot_ses_main_ca_ed283f_idx'), models.Index(fields=['dashboard_category'], name='chatbot_ses_dashboa_5b95e3_idx'), models.Index(fields=['outcome_type'], name='chatbot_ses_outcome_b92a44_idx'), models.Index(fields=['started_at'], name='chatbot_ses_started_273f45_idx')],
            },
        ),
    ]
