# Generated by Django 6.0.6 on 2026-07-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0011_ticket_tkt_created_status_ix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=100, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_row_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_sync_cursors',
            },
        ),
        migrations.CreateModel(
            name='ChatbotChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('questionType', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_chat_logs',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_cha_session_418751_idx'), models.Index(fields=['questionType'], name='chatbot_cha_questio_6b9301_idx'), models.Index(fields=['external_created_at'], name='chatbot_cha_externa_05536a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotCskhRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_cskh_requests',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_csk_session_10e16f_idx'), models.Index(fields=['status'], name='chatbot_csk_status_da6833_idx'), models.Index(fields=['external_created_at'], name='chatbot_csk_externa_fe487a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('step', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('external_created_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_states',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_sta_session_187a3b_idx'), models.Index(fields=['step'], name='chatbot_sta_step_917189_idx'), models.Index(fields=['external_created_at'], name='chatbot_sta_externa_b93c51_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('dashboard_category', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_type', models.CharField(choices=[('BOT_DONE', 'Chatbot tự xử lý'), ('CCC', 'Chuyển CCC xử lý'), ('SPAM', 'Câu hỏi rác'), ('PENDING', 'Chờ thông tin khách hàng')], db_index=True, max_length=50)),
                ('msg_count_total', models.IntegerField(default=0)),
                ('msg_count_bot_done', models.IntegerField(default=0)),
                ('msg_count_ccc', models.IntegerField(default=0)),
                ('msg_count_spam', models.IntegerField(default=0)),
                ('msg_count_pending', models.IntegerField(default=0)),
                ('has_cskh_state', models.BooleanField(default=False)),
                ('has_cskh_request', models.BooleanField(default=False)),
                ('state_step', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('first_question', models.TextField(blank=True, null=True)),
                ('last_question', models.TextField(blank=True, null=True)),
                ('full_conversation', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to='tickets.ticket')),
            ],
            options={
                'db_table': 'chatbot_session_summaries',
                'indexes': [models.Index(fields=['session_id'], name='chatbot_ses_session_faec20_idx'), models.Index(fields=['dashboard_category'], name='chatbot_ses_dashboa_5b95e3_idx'), models.Index(fields=['outcome_type'], name='chatbot_ses_outcome_b92a44_idx'), models.Index(fields=['started_at'], name='chatbot_ses_started_273f45_idx')],
            },
        ),
    ]
