# Generated by Django 6.0.6 on 2026-07-29 01:35

"""
Bỏ các index bị khai báo hai lần trên cùng một cột.

``session_id`` của ba bảng nguồn vừa có ``db_index=True`` vừa có
``models.Index`` trong Meta; ``ChatbotSessionSummary.session_id`` đã unique
(tự có index) mà vẫn khai thêm Meta index, còn ``outcome_type`` thì trùng y
hệt. Mỗi index thừa là một cây B-tree phải cập nhật ở mọi lần ghi khi sync.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbotsessionsummary',
            name='chatbot_ses_session_faec20_idx',
        ),
        migrations.AlterField(
            model_name='chatbotchatlog',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotcskhrequest',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotsessionsummary',
            name='outcome_type',
            field=models.CharField(choices=[('BOT_DONE', 'Chatbot tự xử lý'), ('CCC', 'Chuyển CCC xử lý'), ('SPAM', 'Câu hỏi rác'), ('PENDING', 'Chờ thông tin khách hàng')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chatbotstate',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
