# Generated by Django 5.2.16 on 2026-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_chatbotsynccursor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbotstate',
            name='chatbot_sta_state_517628_idx',
        ),
        migrations.RenameField(
            model_name='chatbotstate',
            old_name='answer',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='chatbotsessionsummary',
            name='state',
        ),
        migrations.RemoveField(
            model_name='chatbotstate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chatbotstate',
            name='state',
        ),
        migrations.AlterField(
            model_name='chatbotchatlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotcskhrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotsessionsummary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotstate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotsynccursor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='chatbotstate',
            index=models.Index(fields=['step'], name='chatbot_sta_step_917189_idx'),
        ),
    ]
