# Generated by Django 6.0.6 on 2026-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_drop_duplicate_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotchatlog',
            name='chat_mode',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='sender_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='source_name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),

        # Gán nguồn cho các dòng đã nhập trước khi có cột này. Bỏ qua dòng
        # demo (external_id có tiền tố DEMO-) để hai lệnh seed vẫn khớp đúng
        # bản ghi cũ của chúng.
        #
        # Không backfill thì lần sync xpro kế tiếp tra theo
        # (source_name="xpro_chat_logs", external_id=796) sẽ không thấy dòng
        # cũ mang source_name="" và chèn thêm một bản trùng.
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model(
                "chatbots", "ChatbotChatLog"
            ).objects.filter(source_name="")
            .exclude(external_id__startswith="DEMO-")
            .update(source_name="xpro_chat_logs"),
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='msg_count_research',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatbotchatlog',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotsessionsummary',
            name='outcome_type',
            field=models.CharField(choices=[('BOT_DONE', 'Chatbot tự xử lý'), ('CCC', 'Chuyển CCC xử lý'), ('RESEARCH', 'Phân tích / khuyến nghị'), ('SPAM', 'Câu hỏi rác'), ('PENDING', 'Chờ thông tin khách hàng')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='chatbotchatlog',
            constraint=models.UniqueConstraint(fields=('source_name', 'external_id'), name='uq_chatbot_chat_log_source_external'),
        ),
    ]
