# Generated by Django 5.2.16 on 2026-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_remove_chatbotstate_chatbot_sta_state_517628_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='msg_count_bot_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='msg_count_ccc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='msg_count_spam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='msg_count_total',
            field=models.IntegerField(default=0),
        ),
    ]
