# Generated by Django 6.0.6 on 2026-08-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_chatbotchatlog_chat_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='msg_count_unclassified',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatbotsessionsummary',
            name='outcome_type',
            field=models.CharField(choices=[('BOT_DONE', 'Chatbot tự xử lý'), ('CCC', 'Chuyển CCC xử lý'), ('RESEARCH', 'Phân tích / khuyến nghị'), ('SPAM', 'Câu hỏi rác'), ('PENDING', 'Chờ thông tin khách hàng'), ('UNCLASSIFIED', 'Chưa xác định loại')], max_length=50),
        ),
    ]
