# Generated by Django 6.0.6 on 2026-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_chatbotsessionsummary_msg_count_unclassified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotchatlog',
            name='category_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='is_issue_occurrence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='relation_issue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatbotcskhrequest',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatbotcskhrequest',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotcskhrequest',
            name='contact_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='contact_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='dashboard_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotstate',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatbotstate',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotstate',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatbotstate',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
