# Generated by Django 5.2.16 on 2026-07-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_chatbotsessionsummary_msg_count_bot_done_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbotchatlog',
            name='chatbot_cha_categor_3fc160_idx',
        ),
        migrations.AddField(
            model_name='chatbotchatlog',
            name='questionType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='chatbotchatlog',
            index=models.Index(fields=['questionType'], name='chatbot_cha_questio_6b9301_idx'),
        ),
    ]
