# Generated by Django 6.0.6 on 2026-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0005_remove_chatbotchatlog_chatbot_cha_categor_3fc160_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatbotsessionsummary',
            name='chatbot_ses_main_ca_ed283f_idx',
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='has_cskh_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='msg_count_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='state_step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotchatlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotcskhrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotsessionsummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotsessionsummary',
            name='outcome_type',
            field=models.CharField(choices=[('BOT_DONE', 'Chatbot tự xử lý'), ('CCC', 'Chuyển CCC xử lý'), ('SPAM', 'Câu hỏi rác'), ('PENDING', 'Chờ thông tin khách hàng')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chatbotstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotsynccursor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='chatbotsessionsummary',
            name='main_category',
        ),
    ]
