# Generated by Django 6.0.6 on 2026-07-16 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_old_chatbot_tickets(apps, schema_editor):
    """
    Dời các ticket chatbot cũ (trong bảng Ticket chung, source=CHATBOT)
    sang bảng TicketChatbot mới. Idempotent: chạy được cả khi không có ticket cũ.
    """
    Ticket = apps.get_model("tickets", "Ticket")
    TicketChatbot = apps.get_model("chatbots", "TicketChatbot")
    ChatbotSessionSummary = apps.get_model("chatbots", "ChatbotSessionSummary")

    old_tickets = Ticket.objects.filter(source__source_code="CHATBOT")

    for old in old_tickets.iterator():
        session_ref = old.source_ref_id

        # Bỏ qua nếu đã dời rồi (chống chạy lại tạo trùng)
        if session_ref and TicketChatbot.objects.filter(source_ref_id=session_ref).exists():
            continue

        new_ticket = TicketChatbot.objects.create(
            ticket_code=old.ticket_code,
            title=old.title,
            source_ref_id=session_ref,
            request_content=old.request_content,
            handling_solution=old.handling_solution,
            customer_id=old.customer_id,
            customer_account_id=old.customer_account_id,
            link_status="LINKED" if (old.customer_id or old.customer_account_id) else "UNLINKED",
            handling_branch_id=old.handling_branch_id,
            status="CHO_TIEP_NHAN",
            created_at=old.created_at,
            updated_at=old.updated_at,
        )

        # Gắn lại vào các summary đang trỏ tới ticket cũ
        ChatbotSessionSummary.objects.filter(ticket_id=old.id).update(
            ticket_chatbot_id=new_ticket.id
        )


def noop_reverse(apps, schema_editor):
    """Không hoàn tác di trú (dữ liệu đã dời giữ nguyên)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
        ('chatbots', '0006_remove_chatbotsessionsummary_chatbot_ses_main_ca_ed283f_idx_and_more'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('tickets', '0009_ticket_account_link_status_and_code_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('link_status', models.CharField(choices=[('LINKED', 'Đã liên kết KH'), ('UNLINKED', 'Chưa có TK liên kết')], default='UNLINKED', max_length=20)),
                ('dashboard_category', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('request_content', models.TextField(blank=True, null=True)),
                ('full_conversation', models.TextField(blank=True, null=True)),
                ('handling_solution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CHO_TIEP_NHAN', 'Chờ tiếp nhận'), ('TIEP_NHAN', 'Tiếp nhận'), ('CHUYEN_PHONG_BAN', 'Chuyển phòng ban'), ('DANG_XU_LY', 'Đang xử lý'), ('DA_XONG', 'Đã xong (Chờ đóng)'), ('CHO_HUY', 'Chờ hủy')], db_index=True, default='CHO_TIEP_NHAN', max_length=30)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True, null=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_chatbot_tickets', to=settings.AUTH_USER_MODEL)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chatbot_tickets', to='branches.employee')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_tickets', to='customers.customer')),
                ('customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_tickets', to='customers.customeraccount')),
                ('handling_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_chatbot_tickets', to='branches.branch')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chatbot_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_chatbots',
            },
        ),
        migrations.AddField(
            model_name='chatbotsessionsummary',
            name='ticket_chatbot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to='chatbots.ticketchatbot'),
        ),
        migrations.AddIndex(
            model_name='ticketchatbot',
            index=models.Index(fields=['ticket_code'], name='ticket_chat_ticket__788081_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketchatbot',
            index=models.Index(fields=['status'], name='ticket_chat_status_aee008_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketchatbot',
            index=models.Index(fields=['owner_user'], name='ticket_chat_owner_u_3e4e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketchatbot',
            index=models.Index(fields=['link_status'], name='ticket_chat_link_st_f3f608_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketchatbot',
            index=models.Index(fields=['created_at'], name='ticket_chat_created_03c6b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketchatbot',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref_id__isnull', False), models.Q(('source_ref_id', ''), _negated=True)), fields=('source_ref_id',), name='uq_ticket_chatbot_source_ref_id'),
        ),
        migrations.RunPython(migrate_old_chatbot_tickets, noop_reverse),
    ]
