# Generated by Django 6.0.6 on 2026-07-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
        ('chatbots', '0007_ticketchatbot_chatbotsessionsummary_ticket_chatbot_and_more'),
        ('sla', '0006_ticket_account_link_status_and_code_rule'),
        ('tickets', '0009_ticket_account_link_status_and_code_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchatbot',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chatbot_tickets', to='branches.processingunit'),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_tickets', to='tickets.ticketpriority'),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='send_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_tickets', to='sla.slapolicy'),
        ),
    ]
