# Generated by Django 6.0.6 on 2026-07-16 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 6 trạng thái workflow CCC cho ticket chatbot (code, name, sort, is_final)
CHATBOT_STATUSES = [
    ("CHO_TIEP_NHAN", "Chờ tiếp nhận", 1, False),
    ("TIEP_NHAN", "Tiếp nhận", 2, False),
    ("CHUYEN_PHONG_BAN", "Chuyển phòng ban", 3, False),
    ("DANG_XU_LY", "Đang xử lý", 4, False),
    ("DA_XONG", "Đã xong (Chờ đóng)", 5, False),
    ("CHO_HUY", "Chờ hủy", 6, True),
]


def seed_statuses_and_migrate(apps, schema_editor):
    """Seed 6 TicketStatus rồi gán current_status theo giá trị status text cũ."""
    TicketStatus = apps.get_model("tickets", "TicketStatus")
    TicketChatbot = apps.get_model("chatbots", "TicketChatbot")

    code_to_status = {}
    for code, name, sort, is_final in CHATBOT_STATUSES:
        status, _ = TicketStatus.objects.get_or_create(
            status_code=code,
            defaults={
                "status_name": name,
                "sort_order": sort,
                "is_final": is_final,
                "is_active": True,
            },
        )
        code_to_status[code] = status

    # Di trú: cột 'status' text cũ vẫn còn ở bước này (RemoveField chạy sau)
    for ticket in TicketChatbot.objects.all():
        old_code = ticket.status
        status = code_to_status.get(old_code)
        if status:
            ticket.current_status_id = status.id
            ticket.save(update_fields=["current_status"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
        ('chatbots', '0008_ticketchatbot_assigned_unit_ticketchatbot_priority_and_more'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('sla', '0006_ticket_account_link_status_and_code_rule'),
        ('tickets', '0009_ticket_account_link_status_and_code_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketchatbot',
            name='ticket_chat_status_aee008_idx',
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chatbot_tickets', to='tickets.ticketstatus'),
        ),
        migrations.AddIndex(
            model_name='ticketchatbot',
            index=models.Index(fields=['current_status'], name='ticket_chat_current_96e4e6_idx'),
        ),
        # Seed 6 status + di trú status text → current_status (trước khi xóa cột)
        migrations.RunPython(seed_statuses_and_migrate, reverse_noop),
        migrations.RemoveField(
            model_name='ticketchatbot',
            name='status',
        ),
    ]
