# Generated by Django 6.0.6 on 2026-07-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0009_ticketchatbot_status_fk'),
        ('sla', '0006_ticket_account_link_status_and_code_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchatbot',
            name='assignment_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='breach_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='breach_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_tickets', to='sla.slabreachreason'),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='breach_reason_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='processing_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchatbot',
            name='sla_status',
            field=models.CharField(blank=True, choices=[('ON_TIME', 'Đúng hạn'), ('OVERDUE', 'Quá hạn'), ('PROCESSING', 'Đang xử lý')], db_index=True, max_length=30, null=True),
        ),
    ]
