# Generated by Django 6.0.6 on 2026-07-18 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0010_ticketchatbot_assignment_due_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketChatbotActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_ticket_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='chatbots.ticketchatbot')),
            ],
            options={
                'db_table': 'ticket_chatbot_activity_logs',
                'indexes': [models.Index(fields=['ticket'], name='ticket_chat_ticket__e84a9e_idx'), models.Index(fields=['action_type'], name='ticket_chat_action__d2c76e_idx'), models.Index(fields=['created_at'], name='ticket_chat_created_21feba_idx')],
            },
        ),
    ]
