# Generated by Django 6.0.6 on 2026-07-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0013_merge_ticket_chatbot_into_ticket'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketchatbot',
            name='ticket_chat_ticket__788081_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketchatbot',
            name='ticket_chat_owner_u_3e4e4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketchatbot',
            name='ticket_chat_link_st_f3f608_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketchatbot',
            name='ticket_chat_created_03c6b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketchatbot',
            name='ticket_chat_current_96e4e6_idx',
        ),
        migrations.RemoveConstraint(
            model_name='ticketchatbot',
            name='uq_ticket_chatbot_source_ref_id',
        ),
        migrations.RemoveField(
            model_name='chatbotsessionsummary',
            name='ticket_chatbot',
        ),
        migrations.RemoveIndex(
            model_name='ticketchatbotactivitylog',
            name='ticket_chat_ticket__e84a9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketchatbotactivitylog',
            name='ticket_chat_action__d2c76e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketchatbotactivitylog',
            name='ticket_chat_created_21feba_idx',
        ),
        migrations.RemoveField(
            model_name='ticketchatbotactivitylog',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='ticketchatbotactivitylog',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='TicketChatbot',
        ),
        migrations.DeleteModel(
            name='TicketChatbotActivityLog',
        ),
    ]
