# Generated by Django 6.0.6 on 2026-07-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpimetricdefinition',
            name='score_direction',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='score_direction',
        ),
    ]
