# Generated by Django 6.0.6 on 2026-07-14 04:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
        ('kpis', '0003_kpiperiodmetric_frequency_kpiperiodmetric_kpi_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('profile_code', models.CharField(choices=[('SA', 'KPI dành cho SA'), ('SA_SUP', 'KPI dành cho SA_SUP')], max_length=50)),
                ('profile_name', models.CharField(max_length=255)),
                ('target_role_code', models.CharField(choices=[('SA_STAFF', 'Nhân viên SA'), ('SA_SUPERVISOR', 'Nhân viên SA_SUP')], max_length=50)),
                ('total_weight', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kpi_profiles',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KpiSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('section_code', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=255)),
                ('weight_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kpi_sections',
                'ordering': ['profile__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='kpigroup',
            options={'ordering': ['profile__sort_order', 'section__sort_order', 'sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='kpiperiodmetric',
            options={'ordering': ['profile__sort_order', 'group__section__sort_order', 'group__sort_order', 'metric_code', 'id']},
        ),
        migrations.AlterModelOptions(
            name='kpirewardtierconfig',
            options={'ordering': ['profile__sort_order', 'sort_order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='kpigroup',
            name='uq_kpi_group_period_code',
        ),
        migrations.RemoveConstraint(
            model_name='kpiperiodgateconfig',
            name='uq_kpi_period_gate_code',
        ),
        migrations.RemoveConstraint(
            model_name='kpiperiodmetric',
            name='uq_kpi_period_metric_code',
        ),
        migrations.RemoveConstraint(
            model_name='kpirewardtierconfig',
            name='uq_kpi_reward_tier_period_code',
        ),
        migrations.RemoveConstraint(
            model_name='kpiusergateresult',
            name='uq_kpi_user_gate_result',
        ),
        migrations.RemoveConstraint(
            model_name='kpiusermetricresult',
            name='uq_kpi_user_metric_result',
        ),
        migrations.RemoveConstraint(
            model_name='kpiusersummary',
            name='uq_kpi_user_summary',
        ),
        migrations.RemoveConstraint(
            model_name='kpiusertarget',
            name='uq_kpi_user_target',
        ),
        migrations.RemoveIndex(
            model_name='kpiusergateresult',
            name='kpi_user_ga_period__b8d9ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='kpiusermetricresult',
            name='kpi_user_me_period__4804b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='kpiusermetricresult',
            name='kpi_user_me_period__a528b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='kpiusersummary',
            name='kpi_user_su_period__558391_idx',
        ),
        migrations.RemoveIndex(
            model_name='kpiusersummary',
            name='kpi_user_su_period__c733be_idx',
        ),
        migrations.AddField(
            model_name='kpiperiodmetric',
            name='target_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kpiusertarget',
            name='target_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiusertarget',
            name='target_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kpigroup',
            name='weight_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='kpiperiodmetric',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='kpis.kpigroup'),
        ),
        migrations.AlterField(
            model_name='kpiperiodmetric',
            name='measurement_formula',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiperiodmetric',
            name='weight_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='kpiusermetricresult',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Nhập tay'), ('AUTO', 'Tự động')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiusertarget',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='kpiprofile',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='kpis.kpiperiod'),
        ),
        migrations.AddField(
            model_name='kpigroup',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpiperiodgateconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_configs', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpiperiodmetric',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpirewardtierconfig',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_tiers', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpiusergateresult',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gate_results', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpiusermetricresult',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_metric_results', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpiusersummary',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_summaries', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpiusertarget',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_targets', to='kpis.kpiprofile'),
        ),
        migrations.AddIndex(
            model_name='kpiusergateresult',
            index=models.Index(fields=['period', 'profile', 'user'], name='kpi_user_ga_period__06207c_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiusermetricresult',
            index=models.Index(fields=['period', 'profile', 'user'], name='kpi_user_me_period__56418e_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiusermetricresult',
            index=models.Index(fields=['period', 'profile', 'metric'], name='kpi_user_me_period__4913a9_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiusersummary',
            index=models.Index(fields=['period', 'profile', 'branch'], name='kpi_user_su_period__38f36c_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiusersummary',
            index=models.Index(fields=['period', 'profile', 'total_score'], name='kpi_user_su_period__882ae3_idx'),
        ),
        migrations.AddConstraint(
            model_name='kpiperiodgateconfig',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'gate_code'), name='uq_kpi_period_profile_gate_code'),
        ),
        migrations.AddConstraint(
            model_name='kpiperiodmetric',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'metric_code'), name='uq_kpi_period_profile_metric_code'),
        ),
        migrations.AddConstraint(
            model_name='kpirewardtierconfig',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'tier_code'), name='uq_kpi_reward_tier_profile_code'),
        ),
        migrations.AddConstraint(
            model_name='kpiusergateresult',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'gate_config', 'user'), name='uq_kpi_user_gate_result_profile'),
        ),
        migrations.AddConstraint(
            model_name='kpiusermetricresult',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'metric', 'user'), name='uq_kpi_user_metric_result_profile'),
        ),
        migrations.AddConstraint(
            model_name='kpiusersummary',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'user'), name='uq_kpi_user_summary_profile'),
        ),
        migrations.AddConstraint(
            model_name='kpiusertarget',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'metric', 'user'), name='uq_kpi_user_target_profile'),
        ),
        migrations.AddField(
            model_name='kpisection',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kpis.kpiperiod'),
        ),
        migrations.AddField(
            model_name='kpisection',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kpis.kpiprofile'),
        ),
        migrations.AddField(
            model_name='kpigroup',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='kpis.kpisection'),
        ),
        migrations.AddConstraint(
            model_name='kpigroup',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'group_code'), name='uq_kpi_group_period_profile_code'),
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='formula_config',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='formula_key',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='kpi_type',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='metric_definition',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='sort_order',
        ),
        migrations.AddConstraint(
            model_name='kpiprofile',
            constraint=models.UniqueConstraint(fields=('period', 'profile_code'), name='uq_kpi_profile_period_code'),
        ),
        migrations.AddConstraint(
            model_name='kpisection',
            constraint=models.UniqueConstraint(fields=('period', 'profile', 'section_code'), name='uq_kpi_section_period_profile_code'),
        ),
        migrations.DeleteModel(
            name='KpiMetricDefinition',
        ),
    ]
