# Generated by Django 6.0.6 on 2026-07-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0004_kpiprofile_kpisection_alter_kpigroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiperiodmetric',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Ngày'), ('WEEKLY', 'Tuần'), ('MONTHLY', 'Tháng'), ('QUARTERLY', 'Quý / 3 tháng'), ('HALF_YEARLY', '6 tháng'), ('YEARLY', 'Năm'), ('ON_EVENT', 'Khi phát sinh')], db_index=True, default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiperiodmetric',
            name='target_unit',
            field=models.CharField(blank=True, choices=[('COUNT', 'Số lượng'), ('PERCENT', '%')], db_index=True, max_length=20, null=True),
        ),
    ]
