# Generated by Django 6.0.6 on 2026-07-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0005_alter_kpiperiodmetric_frequency_and_more'),
        ('kpis', '0006_kpi_metric_result_windows'),
    ]

    operations = [
    ]
