# Generated by Django 6.0.6 on 2026-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0007_merge_20260714_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiperiodmetric',
            name='target_unit',
            field=models.CharField(blank=True, choices=[('COUNT', 'Số lượng'), ('PERCENT', '%'), ('VND', 'VND')], db_index=True, max_length=20, null=True),
        ),
    ]
