# Generated by Django 6.0.6 on 2026-07-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0008_alter_kpiperiodmetric_target_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiperiodmetric',
            name='work_description',
        ),
    ]
