# Generated by Django 6.0.6 on 2026-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0009_remove_kpiperiodmetric_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiperiodmetric',
            name='target_unit',
            field=models.CharField(blank=True, choices=[('COUNT', 'Số lượng'), ('PERCENT', '%'), ('VND', 'VND'), ('SCORE', 'Điểm')], db_index=True, max_length=20, null=True),
        ),
    ]
