# Generated by Django 6.0.6 on 2026-07-27 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_delete_processingunit_delete_processingunitmember'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('kpis', '0010_alter_kpiperiodmetric_target_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='market',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='order_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='side',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='stock_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='source_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_code'], name='transaction_transac_919c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['stock_code'], name='transaction_stock_c_77ea76_idx'),
        ),
    ]
