# Generated by Django 6.0.6 on 2026-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_delete_processingunit_delete_processingunitmember'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('kpis', '0011_transactionlog_market_transactionlog_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionlog',
            name='transaction_account_8ce6e9_idx',
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['customer_account', 'transaction_date'], name='transaction_custome_23000e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['customer_account', 'stock_code'], name='transaction_custome_aa1c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_date', 'stock_code'], name='transaction_transac_df0ead_idx'),
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='customer',
        ),
    ]
