# Generated by Django 6.0.6 on 2026-08-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0012_remove_transactionlog_transaction_account_8ce6e9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpigroup',
            name='group_type',
            field=models.CharField(choices=[('MANUAL', 'Nhập tay'), ('AUTO', 'Tự động')], max_length=50),
        ),
    ]
