# Generated by Django 6.0.6 on 2026-08-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0013_alter_kpigroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='sell_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='sub_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
