# Generated by Django 6.0.6 on 2026-07-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_group_code_alter_permission_id_alter_role_id_and_more'),
        ('branches', '0004_seed_default_processing_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module_code', 'action_code', 'permission_code', 'id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['group_code', 'role_code', 'id']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user_id', 'role_id', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='uq_user_role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='scope_type',
        ),
        migrations.AddField(
            model_name='role',
            name='default_scope_type',
            field=models.CharField(choices=[('OWN', 'Cá nhân'), ('ORGANIZATION_UNIT', 'Đơn vị tổ chức'), ('BRANCH', 'Chi nhánh'), ('MULTI_BRANCH', 'Nhiều chi nhánh'), ('ALL', 'Toàn hệ thống')], db_index=True, default='OWN', max_length=50),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbranchaccess',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='userbranchaccess',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_scopes', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='include_descendants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
