# Generated by Django 6.0.6 on 2026-07-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permission_options_alter_role_options_and_more'),
        ('branches', '0005_employeeorganizationmembership_organizationunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_scopes', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('OWN', 'Cá nhân'), ('ORGANIZATION_UNIT', 'Đơn vị tổ chức'), ('BRANCH', 'Chi nhánh'), ('MULTI_BRANCH', 'Nhiều chi nhánh'), ('ALL', 'Toàn hệ thống')], db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='group_code',
            field=models.CharField(db_index=True, default='CCC', help_text='Nhóm nghiệp vụ của role, ví dụ GLOBAL, CCC, SALE_ADMIN, IT, ACCOUNTING. Không dùng trường này để xác định phòng ban.', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userbranchaccess',
            index=models.Index(fields=['user', 'is_active'], name='user_branch_user_id_f2dafb_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='user_roles_user_id_4ec42c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='user_roles_role_id_57352b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['scope_type'], name='user_roles_scope_t_e93b89_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['organization_unit'], name='user_roles_organiz_fe72d7_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['branch'], name='user_roles_branch__c6659d_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['valid_from', 'valid_to'], name='user_roles_valid_f_60cc27_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'OWN')), fields=('user', 'role'), name='uq_active_user_role_own'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'ALL')), fields=('user', 'role'), name='uq_active_user_role_all'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'MULTI_BRANCH')), fields=('user', 'role'), name='uq_active_user_role_multi_branch'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'BRANCH')), fields=('user', 'role', 'branch'), name='uq_active_user_role_branch'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('scope_type', 'ORGANIZATION_UNIT')), fields=('user', 'role', 'organization_unit'), name='uq_active_user_role_organization_unit'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='ck_user_role_valid_to_after_from'),
        ),
    ]
