# Generated by Django 6.0.6 on 2026-07-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='branches.branch')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='ProcessingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('unit_code', models.CharField(max_length=50, unique=True)),
                ('unit_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_processing_units', to='branches.branch')),
            ],
            options={
                'db_table': 'processing_units',
            },
        ),
        migrations.CreateModel(
            name='ProcessingUnitMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('unit_role', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_unit_memberships', to='branches.employee')),
                ('processing_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='branches.processingunit')),
            ],
            options={
                'db_table': 'processing_unit_members',
                'indexes': [models.Index(fields=['processing_unit'], name='processing__process_de04bc_idx'), models.Index(fields=['employee'], name='processing__employe_043f9c_idx'), models.Index(fields=['unit_role'], name='processing__unit_ro_05dd8b_idx')],
                'constraints': [models.UniqueConstraint(fields=('processing_unit', 'employee'), name='uq_processing_unit_employee')],
            },
        ),
    ]
