# Generated by Django 6.0.6 on 2026-07-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id_alter_employee_id_and_more'),
    ]

    operations = [
    ]
