# Generated by Django 6.0.6 on 2026-07-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_seed_default_processing_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('responsibility', models.CharField(choices=[('MEMBER', 'Thành viên'), ('STAFF', 'Nhân viên'), ('SUPERVISOR', 'Giám sát'), ('MANAGER', 'Quản lý'), ('HEAD', 'Trưởng đơn vị'), ('COORDINATOR', 'Điều phối')], db_index=True, default='MEMBER', max_length=50)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_organization_memberships',
                'ordering': ['employee_id', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('unit_code', models.CharField(max_length=50, unique=True)),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('COMPANY', 'Công ty'), ('DIVISION', 'Khối'), ('CENTER', 'Trung tâm'), ('DEPARTMENT', 'Phòng ban'), ('TEAM', 'Nhóm'), ('PROCESSING_UNIT', 'Đơn vị xử lý'), ('PROJECT', 'Dự án'), ('OTHER', 'Khác')], db_index=True, default='DEPARTMENT', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_ticket_assignable', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'organization_units',
                'ordering': ['sort_order', 'unit_name', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='processingunit',
            name='default_branch',
        ),
        migrations.RemoveIndex(
            model_name='processingunitmember',
            name='processing__process_de04bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='processingunitmember',
            name='processing__employe_043f9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='processingunitmember',
            name='processing__unit_ro_05dd8b_idx',
        ),
        migrations.RemoveConstraint(
            model_name='processingunitmember',
            name='uq_processing_unit_employee',
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name', 'id']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Ngừng hoạt động')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch'], name='employees_branch__ebcd19_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employees_status_0192ac_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employees_employe_6fc092_idx'),
        ),
        migrations.AddField(
            model_name='employeeorganizationmembership',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to='branches.employee'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='branches.organizationunit'),
        ),
        migrations.AddField(
            model_name='employeeorganizationmembership',
            name='organization_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_memberships', to='branches.organizationunit'),
        ),
        migrations.RemoveField(
            model_name='processingunitmember',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='processingunitmember',
            name='processing_unit',
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['unit_code'], name='organizatio_unit_co_102d86_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['unit_type'], name='organizatio_unit_ty_63f4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['parent'], name='organizatio_parent__5e7ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['branch'], name='organizatio_branch__45252c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['is_active', 'is_ticket_assignable'], name='organizatio_is_acti_529ba7_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationunit',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='ck_organization_unit_not_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='organizationunit',
            constraint=models.UniqueConstraint(fields=('branch', 'parent', 'unit_name'), name='uq_organization_unit_name_in_parent', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='employeeorganizationmembership',
            index=models.Index(fields=['employee', 'is_active'], name='employee_or_employe_86d960_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeorganizationmembership',
            index=models.Index(fields=['organization_unit', 'is_active'], name='employee_or_organiz_dc4bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeorganizationmembership',
            index=models.Index(fields=['responsibility'], name='employee_or_respons_a94979_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeorganizationmembership',
            index=models.Index(fields=['is_primary'], name='employee_or_is_prim_f5de5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeorganizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization_unit', 'employee'), name='uq_active_employee_organization_membership'),
        ),
        migrations.AddConstraint(
            model_name='employeeorganizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('employee',), name='uq_primary_organization_membership_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeorganizationmembership',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('joined_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='ck_membership_left_after_joined'),
        ),
    ]
