# Generated by Django 6.0.6 on 2026-07-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_employeeorganizationmembership_organizationunit_and_more'),
        ('sla', '0007_ticketorganizationunitslatracking_and_more'),
        ('tickets', '0013_remove_ticketassignment_ticket_assi_to_unit_3e3d44_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessingUnit',
        ),
        migrations.DeleteModel(
            name='ProcessingUnitMember',
        ),
    ]
