# Generated by Django 6.0.6 on 2026-08-12 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_admin', '0002_sa_record_dashboard_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaIcpRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('call_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icp_rules', to='sale_admin.sacallresult')),
                ('icp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sale_admin.saicpgroup')),
                ('interest_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icp_rules', to='sale_admin.sainterestlevel')),
            ],
            options={
                'db_table': 'sa_icp_rules',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
