# Generated by Django 6.0.6 on 2026-08-27 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_delete_processingunit_delete_processingunitmember'),
        ('customers', '0004_alter_company_id_alter_customer_id_and_more'),
        ('sale_admin', '0003_saicprule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sa_products',
                'ordering': ['-usage_count', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sarecord',
            name='introduced_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='introduced_product_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='sale_admin.saproduct'),
        ),
        migrations.AddIndex(
            model_name='sarecord',
            index=models.Index(fields=['introduced_product_obj'], name='sa_records_introdu_b8185e_idx'),
        ),
    ]
