# Generated by Django 6.0.6 on 2026-08-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_admin', '0004_saproduct_sarecord_introduced_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaSupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sa_support_categories',
                'ordering': ['-usage_count', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sarecord',
            name='support_info_category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sarecord',
            name='support_info_category_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_records', to='sale_admin.sasupportcategory'),
        ),
    ]
