# Generated by Django 6.0.6 on 2026-07-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_remove_kpimetricdefinition_score_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiperiodmetric',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kpiperiodmetric',
            name='kpi_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALE_CSKH', 'Sale/CSKH')], db_index=True, default='ADMIN', max_length=50),
        ),
        migrations.AddField(
            model_name='kpiperiodmetric',
            name='measurement_formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiperiodmetric',
            name='target_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiperiodmetric',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
